// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: shared/shared.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	FuelType      string                 `protobuf:"bytes,7,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	BodyClass     string                 `protobuf:"bytes,8,opt,name=body_class,json=bodyClass,proto3" json:"body_class,omitempty"`
	DriveType     string                 `protobuf:"bytes,9,opt,name=drive_type,json=driveType,proto3" json:"drive_type,omitempty"`
	Transmission  string                 `protobuf:"bytes,10,opt,name=transmission,proto3" json:"transmission,omitempty"`
	IsNew         bool                   `protobuf:"varint,11,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	City          string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,13,opt,name=district,proto3" json:"district,omitempty"`
	State         string                 `protobuf:"bytes,14,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,15,opt,name=country,proto3" json:"country,omitempty"`
	LastSeen      string                 `protobuf:"bytes,16,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IsSold        bool                   `protobuf:"varint,17,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	DealerId      int32                  `protobuf:"varint,18,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingSummary) Reset() {
	*x = ListingSummary{}
	mi := &file_shared_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingSummary) ProtoMessage() {}

func (x *ListingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_shared_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingSummary.ProtoReflect.Descriptor instead.
func (*ListingSummary) Descriptor() ([]byte, []int) {
	return file_shared_shared_proto_rawDescGZIP(), []int{0}
}

func (x *ListingSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingSummary) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingSummary) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingSummary) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingSummary) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingSummary) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingSummary) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *ListingSummary) GetBodyClass() string {
	if x != nil {
		return x.BodyClass
	}
	return ""
}

func (x *ListingSummary) GetDriveType() string {
	if x != nil {
		return x.DriveType
	}
	return ""
}

func (x *ListingSummary) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *ListingSummary) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *ListingSummary) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListingSummary) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ListingSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListingSummary) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListingSummary) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *ListingSummary) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

func (x *ListingSummary) GetDealerId() int32 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

type ListingDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`
	Make          string                 `protobuf:"bytes,3,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,7,opt,name=mileage,proto3" json:"mileage,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	BodyClass     string                 `protobuf:"bytes,9,opt,name=body_class,json=bodyClass,proto3" json:"body_class,omitempty"`
	DriveType     string                 `protobuf:"bytes,10,opt,name=drive_type,json=driveType,proto3" json:"drive_type,omitempty"`
	Transmission  string                 `protobuf:"bytes,11,opt,name=transmission,proto3" json:"transmission,omitempty"`
	IsNew         bool                   `protobuf:"varint,12,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	City          string                 `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,14,opt,name=district,proto3" json:"district,omitempty"`
	State         string                 `protobuf:"bytes,15,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,16,opt,name=country,proto3" json:"country,omitempty"`
	Trim          string                 `protobuf:"bytes,17,opt,name=trim,proto3" json:"trim,omitempty"`
	Color         string                 `protobuf:"bytes,18,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,19,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	Description   string                 `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,21,rep,name=images,proto3" json:"images,omitempty"`
	LastSeen      string                 `protobuf:"bytes,22,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IsSold        bool                   `protobuf:"varint,23,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetails) Reset() {
	*x = ListingDetails{}
	mi := &file_shared_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetails) ProtoMessage() {}

func (x *ListingDetails) ProtoReflect() protoreflect.Message {
	mi := &file_shared_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetails.ProtoReflect.Descriptor instead.
func (*ListingDetails) Descriptor() ([]byte, []int) {
	return file_shared_shared_proto_rawDescGZIP(), []int{1}
}

func (x *ListingDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingDetails) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *ListingDetails) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingDetails) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingDetails) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingDetails) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingDetails) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *ListingDetails) GetBodyClass() string {
	if x != nil {
		return x.BodyClass
	}
	return ""
}

func (x *ListingDetails) GetDriveType() string {
	if x != nil {
		return x.DriveType
	}
	return ""
}

func (x *ListingDetails) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *ListingDetails) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *ListingDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListingDetails) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ListingDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListingDetails) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListingDetails) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *ListingDetails) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ListingDetails) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *ListingDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingDetails) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ListingDetails) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *ListingDetails) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

var File_shared_shared_proto protoreflect.FileDescriptor

const file_shared_shared_proto_rawDesc = "" +
	"\n" +
	"\x13shared/shared.proto\x12\x06shared\"\xd7\x03\n" +
	"\x0eListingSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1b\n" +
	"\tfuel_type\x18\a \x01(\tR\bfuelType\x12\x1d\n" +
	"\n" +
	"body_class\x18\b \x01(\tR\tbodyClass\x12\x1d\n" +
	"\n" +
	"drive_type\x18\t \x01(\tR\tdriveType\x12\"\n" +
	"\ftransmission\x18\n" +
	" \x01(\tR\ftransmission\x12\x15\n" +
	"\x06is_new\x18\v \x01(\bR\x05isNew\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\r \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\x0e \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x0f \x01(\tR\acountry\x12\x1b\n" +
	"\tlast_seen\x18\x10 \x01(\tR\blastSeen\x12\x17\n" +
	"\ais_sold\x18\x11 \x01(\bR\x06isSold\x12\x1b\n" +
	"\tdealer_id\x18\x12 \x01(\x05R\bdealerId\"\xd1\x04\n" +
	"\x0eListingDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12\x12\n" +
	"\x04make\x18\x03 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12\x18\n" +
	"\amileage\x18\a \x01(\x05R\amileage\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x1d\n" +
	"\n" +
	"body_class\x18\t \x01(\tR\tbodyClass\x12\x1d\n" +
	"\n" +
	"drive_type\x18\n" +
	" \x01(\tR\tdriveType\x12\"\n" +
	"\ftransmission\x18\v \x01(\tR\ftransmission\x12\x15\n" +
	"\x06is_new\x18\f \x01(\bR\x05isNew\x12\x12\n" +
	"\x04city\x18\r \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x0e \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\x0f \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x10 \x01(\tR\acountry\x12\x12\n" +
	"\x04trim\x18\x11 \x01(\tR\x04trim\x12\x14\n" +
	"\x05color\x18\x12 \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\x13 \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\x14 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x15 \x03(\tR\x06images\x12\x1b\n" +
	"\tlast_seen\x18\x16 \x01(\tR\blastSeen\x12\x17\n" +
	"\ais_sold\x18\x17 \x01(\bR\x06isSoldB\x11Z\x0fservices/sharedb\x06proto3"

var (
	file_shared_shared_proto_rawDescOnce sync.Once
	file_shared_shared_proto_rawDescData []byte
)

func file_shared_shared_proto_rawDescGZIP() []byte {
	file_shared_shared_proto_rawDescOnce.Do(func() {
		file_shared_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_shared_proto_rawDesc), len(file_shared_shared_proto_rawDesc)))
	})
	return file_shared_shared_proto_rawDescData
}

var file_shared_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_shared_proto_goTypes = []any{
	(*ListingSummary)(nil), // 0: shared.ListingSummary
	(*ListingDetails)(nil), // 1: shared.ListingDetails
}
var file_shared_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_shared_proto_init() }
func file_shared_shared_proto_init() {
	if File_shared_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_shared_proto_rawDesc), len(file_shared_shared_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_shared_proto_goTypes,
		DependencyIndexes: file_shared_shared_proto_depIdxs,
		MessageInfos:      file_shared_shared_proto_msgTypes,
	}.Build()
	File_shared_shared_proto = out.File
	file_shared_shared_proto_goTypes = nil
	file_shared_shared_proto_depIdxs = nil
}
