// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search/proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	shared "services/shared"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Make          string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	MinPrice      int64                  `protobuf:"varint,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int64                  `protobuf:"varint,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	MaxMileage    int32                  `protobuf:"varint,6,opt,name=max_mileage,json=maxMileage,proto3" json:"max_mileage,omitempty"`
	FuelType      string                 `protobuf:"bytes,7,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	BodyClass     string                 `protobuf:"bytes,8,opt,name=body_class,json=bodyClass,proto3" json:"body_class,omitempty"`
	DriveType     string                 `protobuf:"bytes,9,opt,name=drive_type,json=driveType,proto3" json:"drive_type,omitempty"`
	Transmission  string                 `protobuf:"bytes,10,opt,name=transmission,proto3" json:"transmission,omitempty"`
	IsNew         *wrapperspb.BoolValue  `protobuf:"bytes,11,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	Page          int32                  `protobuf:"varint,12,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,13,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *SearchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SearchRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SearchRequest) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchRequest) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchRequest) GetMaxMileage() int32 {
	if x != nil {
		return x.MaxMileage
	}
	return 0
}

func (x *SearchRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *SearchRequest) GetBodyClass() string {
	if x != nil {
		return x.BodyClass
	}
	return ""
}

func (x *SearchRequest) GetDriveType() string {
	if x != nil {
		return x.DriveType
	}
	return ""
}

func (x *SearchRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *SearchRequest) GetIsNew() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsNew
	}
	return nil
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Total         int32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Listings      []*shared.ListingSummary `protobuf:"bytes,4,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResponse) GetListings() []*shared.ListingSummary {
	if x != nil {
		return x.Listings
	}
	return nil
}

var File_search_proto_search_proto protoreflect.FileDescriptor

const file_search_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x19search/proto/search.proto\x12\x06search\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13shared/shared.proto\"\x8b\x03\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x03R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x03R\bmaxPrice\x12\x1f\n" +
	"\vmax_mileage\x18\x06 \x01(\x05R\n" +
	"maxMileage\x12\x1b\n" +
	"\tfuel_type\x18\a \x01(\tR\bfuelType\x12\x1d\n" +
	"\n" +
	"body_class\x18\b \x01(\tR\tbodyClass\x12\x1d\n" +
	"\n" +
	"drive_type\x18\t \x01(\tR\tdriveType\x12\"\n" +
	"\ftransmission\x18\n" +
	" \x01(\tR\ftransmission\x121\n" +
	"\x06is_new\x18\v \x01(\v2\x1a.google.protobuf.BoolValueR\x05isNew\x12\x12\n" +
	"\x04page\x18\f \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\r \x01(\x05R\bpageSize\"\x8b\x01\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x122\n" +
	"\blistings\x18\x04 \x03(\v2\x16.shared.ListingSummaryR\blistings2H\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseB\tZ\a./protob\x06proto3"

var (
	file_search_proto_search_proto_rawDescOnce sync.Once
	file_search_proto_search_proto_rawDescData []byte
)

func file_search_proto_search_proto_rawDescGZIP() []byte {
	file_search_proto_search_proto_rawDescOnce.Do(func() {
		file_search_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_search_proto_rawDesc), len(file_search_proto_search_proto_rawDesc)))
	})
	return file_search_proto_search_proto_rawDescData
}

var file_search_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_search_proto_search_proto_goTypes = []any{
	(*SearchRequest)(nil),         // 0: search.SearchRequest
	(*SearchResponse)(nil),        // 1: search.SearchResponse
	(*wrapperspb.BoolValue)(nil),  // 2: google.protobuf.BoolValue
	(*shared.ListingSummary)(nil), // 3: shared.ListingSummary
}
var file_search_proto_search_proto_depIdxs = []int32{
	2, // 0: search.SearchRequest.is_new:type_name -> google.protobuf.BoolValue
	3, // 1: search.SearchResponse.listings:type_name -> shared.ListingSummary
	0, // 2: search.SearchService.Search:input_type -> search.SearchRequest
	1, // 3: search.SearchService.Search:output_type -> search.SearchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_proto_search_proto_init() }
func file_search_proto_search_proto_init() {
	if File_search_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_search_proto_rawDesc), len(file_search_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_search_proto_goTypes,
		DependencyIndexes: file_search_proto_search_proto_depIdxs,
		MessageInfos:      file_search_proto_search_proto_msgTypes,
	}.Build()
	File_search_proto_search_proto = out.File
	file_search_proto_search_proto_goTypes = nil
	file_search_proto_search_proto_depIdxs = nil
}
