// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Make          string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	MaxMileage    int32                  `protobuf:"varint,6,opt,name=max_mileage,json=maxMileage,proto3" json:"max_mileage,omitempty"`
	FuelType      string                 `protobuf:"bytes,7,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"` // gasoline, diesel, hybrid, electric
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *SearchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SearchRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SearchRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchRequest) GetMaxMileage() int32 {
	if x != nil {
		return x.MaxMileage
	}
	return 0
}

func (x *SearchRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *SearchRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Listings      []*ListingSummary      `protobuf:"bytes,4,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResponse) GetListings() []*ListingSummary {
	if x != nil {
		return x.Listings
	}
	return nil
}

type ListingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingSummary) Reset() {
	*x = ListingSummary{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingSummary) ProtoMessage() {}

func (x *ListingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingSummary.ProtoReflect.Descriptor instead.
func (*ListingSummary) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *ListingSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingSummary) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingSummary) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingSummary) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingSummary) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingSummary) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingSummary) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListingSummary) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Listing) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Listing) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Listing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *Listing) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Listing) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

type ListingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsRequest) Reset() {
	*x = ListingDetailsRequest{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsRequest) ProtoMessage() {}

func (x *ListingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsRequest.ProtoReflect.Descriptor instead.
func (*ListingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *ListingDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Trim          string                 `protobuf:"bytes,9,opt,name=trim,proto3" json:"trim,omitempty"`
	Transmission  string                 `protobuf:"bytes,10,opt,name=transmission,proto3" json:"transmission,omitempty"` // automatic, manual
	Color         string                 `protobuf:"bytes,11,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,12,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"` // dealer, private
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	ListedAt      string                 `protobuf:"bytes,14,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"` // date-time
	Images        []string               `protobuf:"bytes,15,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsResponse) Reset() {
	*x = ListingDetailsResponse{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsResponse) ProtoMessage() {}

func (x *ListingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsResponse.ProtoReflect.Descriptor instead.
func (*ListingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *ListingDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListingDetailsResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingDetailsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingDetailsResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingDetailsResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingDetailsResponse) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingDetailsResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListingDetailsResponse) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *ListingDetailsResponse) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *ListingDetailsResponse) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *ListingDetailsResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ListingDetailsResponse) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *ListingDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingDetailsResponse) GetListedAt() string {
	if x != nil {
		return x.ListedAt
	}
	return ""
}

func (x *ListingDetailsResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CompareListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsRequest) Reset() {
	*x = CompareListingsRequest{}
	mi := &file_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsRequest) ProtoMessage() {}

func (x *CompareListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsRequest.ProtoReflect.Descriptor instead.
func (*CompareListingsRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{6}
}

func (x *CompareListingsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CompareListingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Listings      []*ListingDetailsResponse `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsResponse) Reset() {
	*x = CompareListingsResponse{}
	mi := &file_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsResponse) ProtoMessage() {}

func (x *CompareListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsResponse.ProtoReflect.Descriptor instead.
func (*CompareListingsResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{7}
}

func (x *CompareListingsResponse) GetListings() []*ListingDetailsResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"\x92\x02\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12\x1f\n" +
	"\vmax_mileage\x18\x06 \x01(\x05R\n" +
	"maxMileage\x12\x1b\n" +
	"\tfuel_type\x18\a \x01(\tR\bfuelType\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\"\x8b\x01\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x122\n" +
	"\blistings\x18\x04 \x03(\v2\x16.search.ListingSummaryR\blistings\"\xc7\x01\n" +
	"\x0eListingSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\"\xc0\x01\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\"'\n" +
	"\x15ListingDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x95\x03\n" +
	"\x16ListingDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x12\n" +
	"\x04trim\x18\t \x01(\tR\x04trim\x12\"\n" +
	"\ftransmission\x18\n" +
	" \x01(\tR\ftransmission\x12\x14\n" +
	"\x05color\x18\v \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\f \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x1b\n" +
	"\tlisted_at\x18\x0e \x01(\tR\blistedAt\x12\x16\n" +
	"\x06images\x18\x0f \x03(\tR\x06images\"*\n" +
	"\x16CompareListingsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"U\n" +
	"\x17CompareListingsResponse\x12:\n" +
	"\blistings\x18\x01 \x03(\v2\x1e.search.ListingDetailsResponseR\blistings2\xf0\x01\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12R\n" +
	"\x11GetListingDetails\x12\x1d.search.ListingDetailsRequest\x1a\x1e.search.ListingDetailsResponse\x12R\n" +
	"\x0fCompareListings\x12\x1e.search.CompareListingsRequest\x1a\x1f.search.CompareListingsResponseB\tZ\a./protob\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_search_proto_goTypes = []any{
	(*SearchRequest)(nil),           // 0: search.SearchRequest
	(*SearchResponse)(nil),          // 1: search.SearchResponse
	(*ListingSummary)(nil),          // 2: search.ListingSummary
	(*Listing)(nil),                 // 3: search.Listing
	(*ListingDetailsRequest)(nil),   // 4: search.ListingDetailsRequest
	(*ListingDetailsResponse)(nil),  // 5: search.ListingDetailsResponse
	(*CompareListingsRequest)(nil),  // 6: search.CompareListingsRequest
	(*CompareListingsResponse)(nil), // 7: search.CompareListingsResponse
}
var file_search_proto_depIdxs = []int32{
	2, // 0: search.SearchResponse.listings:type_name -> search.ListingSummary
	5, // 1: search.CompareListingsResponse.listings:type_name -> search.ListingDetailsResponse
	0, // 2: search.SearchService.Search:input_type -> search.SearchRequest
	4, // 3: search.SearchService.GetListingDetails:input_type -> search.ListingDetailsRequest
	6, // 4: search.SearchService.CompareListings:input_type -> search.CompareListingsRequest
	1, // 5: search.SearchService.Search:output_type -> search.SearchResponse
	5, // 6: search.SearchService.GetListingDetails:output_type -> search.ListingDetailsResponse
	7, // 7: search.SearchService.CompareListings:output_type -> search.CompareListingsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
