apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: vehicles-prod
  labels:
    app: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
        - name: redis
          image: europe-central2-docker.pkg.dev/cn-project-491618/vehicles/redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
