apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: vehicles-prod
type: Opaque
stringData:
  USER_DATABASE_URL: postgres://postgres:uma_password_forte_aqui@127.0.0.1:5432/user_db?sslmode=disable
  USER_POSTGRES_DB: user_db
  USER_POSTGRES_USER: postgres
  USER_POSTGRES_PASSWORD: uma_password_forte_aqui
  FIREBASE_API_KEY: replace-me
