apiVersion: v1
kind: Secret
metadata:
  name: auction-secrets
  namespace: vehicles-prod
type: Opaque
stringData:
  postgres-dsn: postgres://postgres:uma_password_forte_aqui@127.0.0.1:5432/auction_db?sslmode=disable
  gcp-project-id: cn-project-491618
