apiVersion: v1
kind: Service
metadata:
  name: auction
  labels:
    app: auction
spec:
  selector:
    app: auction
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: ws
      port: 8081
      targetPort: ws