apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: vehicles-prod
data:
  AUCTION_GRPC_ADDR: "auction-service:50051"
  CHAT_GRPC_ADDR: "chat-service:50052"
  GEO_GRPC_ADDR: "geographic-market-insights-service:50053"
  LISTING_GRPC_ADDR: "listing-service:50054"
  MARKETPRICE_GRPC_ADDR: "marketprice-service:50055"
  SEARCH_GRPC_ADDR: "search-service:50056"
  SELLER_GRPC_ADDR: "seller-service:50057"
  USER_GRPC_ADDR: "user-service:50058"
  CHAT_WS_ADDR: "ws://chat-service:8080"
  AUCTION_WS_ADDR: "ws://auction-service:8081"
  FIREBASE_PROJECT_ID: "cn-project-491618"