# kubectl create secret generic gateway-secrets \
#   --from-literal=JWT_PUBLIC_KEY_B64=MY_STRONG_SECRET
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  JWT_PUBLIC_KEY_B64: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5d3ArQTlHY1pxK2xSdzBXS0N3NQp6UnlpRkZaS0VHQXljbndJVHdTVUpnUXp2Y2wrdWRwUENJWXByZk1aVDJHcmFDN0lqbTYrc1Y5T2tLRGdFbml6CkY4bFV6WjN6OFA1VGlxY29QdTFpdHJjYm9YaFZhaTloM21DdENCaTJ4TE9ya2dDOVU1ZHVwajFnV3NER2x2emIKVjNLR1B6blh3Qm5qVVpsaHpSRDgreFJxdW1IK285SWFXOTR4U1FyaGx3SWFOWDFWdG5NbzJDZjlCdTAzMXQ4QgpBSG9ESG4wWXl6NlNkNUEzWmUyUmt0MHJVcktpUXBSeFIyRFd5WWJwRVRmb1F0eTQ0MVZWaHJMK09iSG5XTnJtCnlPV0xnbTBqMUZ4czhYS0s1VG1jRFVHOC9SaUZ6UWgzYU1QN0NubHBPakRmb1ZVbXROK2Ura0Z0NEcxK1c5OTYKZHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg
