# kubectl create secret generic gateway-secrets \
#   --from-literal=jwt-secret=MY_STRONG_SECRET
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  jwt-secret: "REPLACE_ME"
