apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vehicles-prod
resources:
  - common/namespace.yaml
  - common/serviceaccount.yaml
  - common/cloudsql-config.yaml
  - listing
  - search
  - chat
  - geographic-market-insights
  - auth
  - user
  - seller
  - marketprice
  - auction
  - gateway
  - ingress_vehicles_prod.yaml
