apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
type: Opaque
stringData:
  GCP_PROJECT_ID: "cn-project-491618"
  POSTGRES_DSN: "postgres://postgres:uma_password_forte_aqui@127.0.0.1:5432/chat_db?sslmode=disable"
  POSTGRES_SCHEMA: "chat-db"
  POSTGRES_TABLE: "chat"
  FTIRESTORE_MESSAGES_COLLECTION: "messages"