apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
type: Opaque
stringData:
  gcp-project-id: "REPLACE"
  postgres-dsn: "REPLACE"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-sa
  annotations:
    iam.gke.io/gcp-service-account: chat-svc@PROJECT_ID.iam.gserviceaccount.com
