apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app: chat
spec:
  selector:
    app: chat
  type: ClusterIP
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
    - name: ws
      port: 8080
      targetPort: ws
