apiVersion: apps/v1
kind: Deployment
metadata:
  name: geographic-market-insights-service
  namespace: vehicles-prod
  labels:
    app: geographic-market-insights-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geographic-market-insights-service
  template:
    metadata:
      labels:
        app: geographic-market-insights-service
    spec:
      serviceAccountName: vehicles-workload-sa
      containers:
        - name: geographic-market-insights-service
          image: europe-central2-docker.pkg.dev/cn-project-491618/vehicles/geographic-market-insights
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 50053
          env:
            - name: GEO_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: geo-secrets
                  key: GEO_DATABASE_URL
          envFrom:
            - configMapRef:
                name: geo-config
          startupProbe:
            grpc:
              port: 50053
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            grpc:
              port: 50053
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 50053
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
          args:
            - "--structured-logs"
            - "--port=5432"
            - "--health-check"
            - "--http-address=0.0.0.0"
            - "$(CLOUD_SQL_INSTANCE)"
          env:
            - name: CLOUD_SQL_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: cloudsql-config
                  key: instance-connection-name
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          startupProbe:
            httpGet:
              path: /startup
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
