apiVersion: v1
kind: Secret
metadata:
  name: geo-secrets
  namespace: vehicles-prod
type: Opaque
stringData:
  postgres-dsn: postgres://postgres:uma_password_forte_aqui@127.0.0.1:5432/geo_db?sslmode=disable
