apiVersion: v1
kind: Service
metadata:
  name: geographic-market-insights
  labels:
    app: geographic-market-insights
spec:
  selector:
    app: geographic-market-insights
  type: ClusterIP
  ports:
    - name: grpc
      port: 50053
      targetPort: grpc
