// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: geographic-maket-insights/proto/geo-market-insights.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_METRIC_TYPE_AVG_PRICE    MetricType = 0
	MetricType_METRIC_TYPE_MEDIAN_PRICE MetricType = 1
	MetricType_METRIC_TYPE_COUNT        MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_AVG_PRICE",
		1: "METRIC_TYPE_MEDIAN_PRICE",
		2: "METRIC_TYPE_COUNT",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_AVG_PRICE":    0,
		"METRIC_TYPE_MEDIAN_PRICE": 1,
		"METRIC_TYPE_COUNT":        2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{0}
}

type GroupBy int32

const (
	GroupBy_GROUP_BY_DISTRICT GroupBy = 0
	GroupBy_GROUP_BY_CITY     GroupBy = 1
	GroupBy_GROUP_BY_COUNTRY  GroupBy = 2
)

// Enum value maps for GroupBy.
var (
	GroupBy_name = map[int32]string{
		0: "GROUP_BY_DISTRICT",
		1: "GROUP_BY_CITY",
		2: "GROUP_BY_COUNTRY",
	}
	GroupBy_value = map[string]int32{
		"GROUP_BY_DISTRICT": 0,
		"GROUP_BY_CITY":     1,
		"GROUP_BY_COUNTRY":  2,
	}
)

func (x GroupBy) Enum() *GroupBy {
	p := new(GroupBy)
	*p = x
	return p
}

func (x GroupBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupBy) Descriptor() protoreflect.EnumDescriptor {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[1].Descriptor()
}

func (GroupBy) Type() protoreflect.EnumType {
	return &file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[1]
}

func (x GroupBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupBy.Descriptor instead.
func (GroupBy) EnumDescriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{1}
}

type SortBy int32

const (
	SortBy_SORT_BY_AVG_PRICE SortBy = 0
	SortBy_SORT_BY_COUNT     SortBy = 1
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_AVG_PRICE",
		1: "SORT_BY_COUNT",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_AVG_PRICE": 0,
		"SORT_BY_COUNT":     1,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[2].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[2]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{2}
}

type Order int32

const (
	Order_ORDER_ASC  Order = 0
	Order_ORDER_DESC Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_ASC",
		1: "ORDER_DESC",
	}
	Order_value = map[string]int32{
		"ORDER_ASC":  0,
		"ORDER_DESC": 1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[3].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes[3]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{3}
}

type AggregatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Metrics       []MetricType           `protobuf:"varint,3,rep,packed,name=metrics,proto3,enum=geo_market_insights.MetricType" json:"metrics,omitempty"`
	GroupBy       GroupBy                `protobuf:"varint,4,opt,name=group_by,json=groupBy,proto3,enum=geo_market_insights.GroupBy" json:"group_by,omitempty"`
	Locations     *Locations             `protobuf:"bytes,5,opt,name=locations,proto3,oneof" json:"locations,omitempty"`
	YearFrom      *int32                 `protobuf:"varint,6,opt,name=year_from,json=yearFrom,proto3,oneof" json:"year_from,omitempty"`
	YearTo        *int32                 `protobuf:"varint,7,opt,name=year_to,json=yearTo,proto3,oneof" json:"year_to,omitempty"`
	FuelType      *string                `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3,oneof" json:"fuel_type,omitempty"`
	Limit         *int32                 `protobuf:"varint,9,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Skip          *int32                 `protobuf:"varint,10,opt,name=skip,proto3,oneof" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatesRequest) Reset() {
	*x = AggregatesRequest{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatesRequest) ProtoMessage() {}

func (x *AggregatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatesRequest.ProtoReflect.Descriptor instead.
func (*AggregatesRequest) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{0}
}

func (x *AggregatesRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *AggregatesRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AggregatesRequest) GetMetrics() []MetricType {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AggregatesRequest) GetGroupBy() GroupBy {
	if x != nil {
		return x.GroupBy
	}
	return GroupBy_GROUP_BY_DISTRICT
}

func (x *AggregatesRequest) GetLocations() *Locations {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *AggregatesRequest) GetYearFrom() int32 {
	if x != nil && x.YearFrom != nil {
		return *x.YearFrom
	}
	return 0
}

func (x *AggregatesRequest) GetYearTo() int32 {
	if x != nil && x.YearTo != nil {
		return *x.YearTo
	}
	return 0
}

func (x *AggregatesRequest) GetFuelType() string {
	if x != nil && x.FuelType != nil {
		return *x.FuelType
	}
	return ""
}

func (x *AggregatesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *AggregatesRequest) GetSkip() int32 {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return 0
}

type AggregatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggregates    []*Aggregates          `protobuf:"bytes,1,rep,name=aggregates,proto3" json:"aggregates,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatesResponse) Reset() {
	*x = AggregatesResponse{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatesResponse) ProtoMessage() {}

func (x *AggregatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatesResponse.ProtoReflect.Descriptor instead.
func (*AggregatesResponse) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{1}
}

func (x *AggregatesResponse) GetAggregates() []*Aggregates {
	if x != nil {
		return x.Aggregates
	}
	return nil
}

func (x *AggregatesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Aggregates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	AvgPrice      int32                  `protobuf:"varint,2,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	MedianPrice   int32                  `protobuf:"varint,3,opt,name=median_price,json=medianPrice,proto3" json:"median_price,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aggregates) Reset() {
	*x = Aggregates{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aggregates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregates) ProtoMessage() {}

func (x *Aggregates) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregates.ProtoReflect.Descriptor instead.
func (*Aggregates) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{2}
}

func (x *Aggregates) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Aggregates) GetAvgPrice() int32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Aggregates) GetMedianPrice() int32 {
	if x != nil {
		return x.MedianPrice
	}
	return 0
}

func (x *Aggregates) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PriceComparisonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	GroupBy       GroupBy                `protobuf:"varint,4,opt,name=group_by,json=groupBy,proto3,enum=geo_market_insights.GroupBy" json:"group_by,omitempty"`
	SortBy        *SortBy                `protobuf:"varint,5,opt,name=sort_by,json=sortBy,proto3,enum=geo_market_insights.SortBy,oneof" json:"sort_by,omitempty"`
	Order         *Order                 `protobuf:"varint,6,opt,name=order,proto3,enum=geo_market_insights.Order,oneof" json:"order,omitempty"`
	Limit         *int32                 `protobuf:"varint,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Skip          *int32                 `protobuf:"varint,8,opt,name=skip,proto3,oneof" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceComparisonRequest) Reset() {
	*x = PriceComparisonRequest{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceComparisonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceComparisonRequest) ProtoMessage() {}

func (x *PriceComparisonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceComparisonRequest.ProtoReflect.Descriptor instead.
func (*PriceComparisonRequest) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{3}
}

func (x *PriceComparisonRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *PriceComparisonRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PriceComparisonRequest) GetGroupBy() GroupBy {
	if x != nil {
		return x.GroupBy
	}
	return GroupBy_GROUP_BY_DISTRICT
}

func (x *PriceComparisonRequest) GetSortBy() SortBy {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return SortBy_SORT_BY_AVG_PRICE
}

func (x *PriceComparisonRequest) GetOrder() Order {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return Order_ORDER_ASC
}

func (x *PriceComparisonRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *PriceComparisonRequest) GetSkip() int32 {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return 0
}

type PriceComparisonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comparisons   []*Comparisons         `protobuf:"bytes,1,rep,name=comparisons,proto3" json:"comparisons,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceComparisonResponse) Reset() {
	*x = PriceComparisonResponse{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceComparisonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceComparisonResponse) ProtoMessage() {}

func (x *PriceComparisonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceComparisonResponse.ProtoReflect.Descriptor instead.
func (*PriceComparisonResponse) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{4}
}

func (x *PriceComparisonResponse) GetComparisons() []*Comparisons {
	if x != nil {
		return x.Comparisons
	}
	return nil
}

func (x *PriceComparisonResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ByLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Location      *string                `protobuf:"bytes,3,opt,name=location,proto3,oneof" json:"location,omitempty"`
	YearFrom      *int32                 `protobuf:"varint,4,opt,name=year_from,json=yearFrom,proto3,oneof" json:"year_from,omitempty"`
	YearTo        *int32                 `protobuf:"varint,5,opt,name=year_to,json=yearTo,proto3,oneof" json:"year_to,omitempty"`
	FuelType      *string                `protobuf:"bytes,6,opt,name=fuel_type,json=fuelType,proto3,oneof" json:"fuel_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByLocationRequest) Reset() {
	*x = ByLocationRequest{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByLocationRequest) ProtoMessage() {}

func (x *ByLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByLocationRequest.ProtoReflect.Descriptor instead.
func (*ByLocationRequest) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{5}
}

func (x *ByLocationRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ByLocationRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ByLocationRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *ByLocationRequest) GetYearFrom() int32 {
	if x != nil && x.YearFrom != nil {
		return *x.YearFrom
	}
	return 0
}

func (x *ByLocationRequest) GetYearTo() int32 {
	if x != nil && x.YearTo != nil {
		return *x.YearTo
	}
	return 0
}

func (x *ByLocationRequest) GetFuelType() string {
	if x != nil && x.FuelType != nil {
		return *x.FuelType
	}
	return ""
}

type ByLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByLocationResponse) Reset() {
	*x = ByLocationResponse{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByLocationResponse) ProtoMessage() {}

func (x *ByLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByLocationResponse.ProtoReflect.Descriptor instead.
func (*ByLocationResponse) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{6}
}

func (x *ByLocationResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPrice      int32                  `protobuf:"varint,1,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,2,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	AvgPrice      int32                  `protobuf:"varint,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	MedianPrice   int32                  `protobuf:"varint,4,opt,name=median_price,json=medianPrice,proto3" json:"median_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{7}
}

func (x *Stats) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *Stats) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *Stats) GetAvgPrice() int32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Stats) GetMedianPrice() int32 {
	if x != nil {
		return x.MedianPrice
	}
	return 0
}

type Comparisons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	AveragePrice  int32                  `protobuf:"varint,2,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	ListingCount  int32                  `protobuf:"varint,3,opt,name=listing_count,json=listingCount,proto3" json:"listing_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comparisons) Reset() {
	*x = Comparisons{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comparisons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comparisons) ProtoMessage() {}

func (x *Comparisons) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comparisons.ProtoReflect.Descriptor instead.
func (*Comparisons) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{8}
}

func (x *Comparisons) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Comparisons) GetAveragePrice() int32 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *Comparisons) GetListingCount() int32 {
	if x != nil {
		return x.ListingCount
	}
	return 0
}

type Locations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      []string               `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locations) Reset() {
	*x = Locations{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locations) ProtoMessage() {}

func (x *Locations) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locations.ProtoReflect.Descriptor instead.
func (*Locations) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{9}
}

func (x *Locations) GetLocation() []string {
	if x != nil {
		return x.Location
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	NextSkip      *int32                 `protobuf:"varint,4,opt,name=next_skip,json=nextSkip,proto3,oneof" json:"next_skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP(), []int{10}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Pagination) GetNextSkip() int32 {
	if x != nil && x.NextSkip != nil {
		return *x.NextSkip
	}
	return 0
}

var File_geographic_maket_insights_proto_geo_market_insights_proto protoreflect.FileDescriptor

const file_geographic_maket_insights_proto_geo_market_insights_proto_rawDesc = "" +
	"\n" +
	"9geographic-maket-insights/proto/geo-market-insights.proto\x12\x13geo_market_insights\"\xd5\x03\n" +
	"\x11AggregatesRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x129\n" +
	"\ametrics\x18\x03 \x03(\x0e2\x1f.geo_market_insights.MetricTypeR\ametrics\x127\n" +
	"\bgroup_by\x18\x04 \x01(\x0e2\x1c.geo_market_insights.GroupByR\agroupBy\x12A\n" +
	"\tlocations\x18\x05 \x01(\v2\x1e.geo_market_insights.LocationsH\x00R\tlocations\x88\x01\x01\x12 \n" +
	"\tyear_from\x18\x06 \x01(\x05H\x01R\byearFrom\x88\x01\x01\x12\x1c\n" +
	"\ayear_to\x18\a \x01(\x05H\x02R\x06yearTo\x88\x01\x01\x12 \n" +
	"\tfuel_type\x18\b \x01(\tH\x03R\bfuelType\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\t \x01(\x05H\x04R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04skip\x18\n" +
	" \x01(\x05H\x05R\x04skip\x88\x01\x01B\f\n" +
	"\n" +
	"_locationsB\f\n" +
	"\n" +
	"_year_fromB\n" +
	"\n" +
	"\b_year_toB\f\n" +
	"\n" +
	"_fuel_typeB\b\n" +
	"\x06_limitB\a\n" +
	"\x05_skip\"\x96\x01\n" +
	"\x12AggregatesResponse\x12?\n" +
	"\n" +
	"aggregates\x18\x01 \x03(\v2\x1f.geo_market_insights.AggregatesR\n" +
	"aggregates\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.geo_market_insights.PaginationR\n" +
	"pagination\"~\n" +
	"\n" +
	"Aggregates\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x1b\n" +
	"\tavg_price\x18\x02 \x01(\x05R\bavgPrice\x12!\n" +
	"\fmedian_price\x18\x03 \x01(\x05R\vmedianPrice\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"\xcc\x02\n" +
	"\x16PriceComparisonRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x127\n" +
	"\bgroup_by\x18\x04 \x01(\x0e2\x1c.geo_market_insights.GroupByR\agroupBy\x129\n" +
	"\asort_by\x18\x05 \x01(\x0e2\x1b.geo_market_insights.SortByH\x00R\x06sortBy\x88\x01\x01\x125\n" +
	"\x05order\x18\x06 \x01(\x0e2\x1a.geo_market_insights.OrderH\x01R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\a \x01(\x05H\x02R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04skip\x18\b \x01(\x05H\x03R\x04skip\x88\x01\x01B\n" +
	"\n" +
	"\b_sort_byB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\a\n" +
	"\x05_skip\"\x9e\x01\n" +
	"\x17PriceComparisonResponse\x12B\n" +
	"\vcomparisons\x18\x01 \x03(\v2 .geo_market_insights.ComparisonsR\vcomparisons\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.geo_market_insights.PaginationR\n" +
	"pagination\"\xf7\x01\n" +
	"\x11ByLocationRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\blocation\x18\x03 \x01(\tH\x00R\blocation\x88\x01\x01\x12 \n" +
	"\tyear_from\x18\x04 \x01(\x05H\x01R\byearFrom\x88\x01\x01\x12\x1c\n" +
	"\ayear_to\x18\x05 \x01(\x05H\x02R\x06yearTo\x88\x01\x01\x12 \n" +
	"\tfuel_type\x18\x06 \x01(\tH\x03R\bfuelType\x88\x01\x01B\v\n" +
	"\t_locationB\f\n" +
	"\n" +
	"_year_fromB\n" +
	"\n" +
	"\b_year_toB\f\n" +
	"\n" +
	"_fuel_type\"F\n" +
	"\x12ByLocationResponse\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.geo_market_insights.StatsR\x05stats\"\x81\x01\n" +
	"\x05Stats\x12\x1b\n" +
	"\tmin_price\x18\x01 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x02 \x01(\x05R\bmaxPrice\x12\x1b\n" +
	"\tavg_price\x18\x03 \x01(\x05R\bavgPrice\x12!\n" +
	"\fmedian_price\x18\x04 \x01(\x05R\vmedianPrice\"s\n" +
	"\vComparisons\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12#\n" +
	"\raverage_price\x18\x02 \x01(\x05R\faveragePrice\x12#\n" +
	"\rlisting_count\x18\x03 \x01(\x05R\flistingCount\"'\n" +
	"\tLocations\x12\x1a\n" +
	"\blocation\x18\x01 \x03(\tR\blocation\"\x81\x01\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12 \n" +
	"\tnext_skip\x18\x04 \x01(\x05H\x00R\bnextSkip\x88\x01\x01B\f\n" +
	"\n" +
	"_next_skip*\\\n" +
	"\n" +
	"MetricType\x12\x19\n" +
	"\x15METRIC_TYPE_AVG_PRICE\x10\x00\x12\x1c\n" +
	"\x18METRIC_TYPE_MEDIAN_PRICE\x10\x01\x12\x15\n" +
	"\x11METRIC_TYPE_COUNT\x10\x02*I\n" +
	"\aGroupBy\x12\x15\n" +
	"\x11GROUP_BY_DISTRICT\x10\x00\x12\x11\n" +
	"\rGROUP_BY_CITY\x10\x01\x12\x14\n" +
	"\x10GROUP_BY_COUNTRY\x10\x02*2\n" +
	"\x06SortBy\x12\x15\n" +
	"\x11SORT_BY_AVG_PRICE\x10\x00\x12\x11\n" +
	"\rSORT_BY_COUNT\x10\x01*&\n" +
	"\x05Order\x12\r\n" +
	"\tORDER_ASC\x10\x00\x12\x0e\n" +
	"\n" +
	"ORDER_DESC\x10\x012\xc6\x02\n" +
	"\x18GeoMarketInsightsService\x12]\n" +
	"\n" +
	"Aggregates\x12&.geo_market_insights.AggregatesRequest\x1a'.geo_market_insights.AggregatesResponse\x12l\n" +
	"\x0fPriceComparison\x12+.geo_market_insights.PriceComparisonRequest\x1a,.geo_market_insights.PriceComparisonResponse\x12]\n" +
	"\n" +
	"ByLocation\x12&.geo_market_insights.ByLocationRequest\x1a'.geo_market_insights.ByLocationResponseB\tZ\a./protob\x06proto3"

var (
	file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescOnce sync.Once
	file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescData []byte
)

func file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescGZIP() []byte {
	file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescOnce.Do(func() {
		file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geographic_maket_insights_proto_geo_market_insights_proto_rawDesc), len(file_geographic_maket_insights_proto_geo_market_insights_proto_rawDesc)))
	})
	return file_geographic_maket_insights_proto_geo_market_insights_proto_rawDescData
}

var file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_geographic_maket_insights_proto_geo_market_insights_proto_goTypes = []any{
	(MetricType)(0),                 // 0: geo_market_insights.MetricType
	(GroupBy)(0),                    // 1: geo_market_insights.GroupBy
	(SortBy)(0),                     // 2: geo_market_insights.SortBy
	(Order)(0),                      // 3: geo_market_insights.Order
	(*AggregatesRequest)(nil),       // 4: geo_market_insights.AggregatesRequest
	(*AggregatesResponse)(nil),      // 5: geo_market_insights.AggregatesResponse
	(*Aggregates)(nil),              // 6: geo_market_insights.Aggregates
	(*PriceComparisonRequest)(nil),  // 7: geo_market_insights.PriceComparisonRequest
	(*PriceComparisonResponse)(nil), // 8: geo_market_insights.PriceComparisonResponse
	(*ByLocationRequest)(nil),       // 9: geo_market_insights.ByLocationRequest
	(*ByLocationResponse)(nil),      // 10: geo_market_insights.ByLocationResponse
	(*Stats)(nil),                   // 11: geo_market_insights.Stats
	(*Comparisons)(nil),             // 12: geo_market_insights.Comparisons
	(*Locations)(nil),               // 13: geo_market_insights.Locations
	(*Pagination)(nil),              // 14: geo_market_insights.Pagination
}
var file_geographic_maket_insights_proto_geo_market_insights_proto_depIdxs = []int32{
	0,  // 0: geo_market_insights.AggregatesRequest.metrics:type_name -> geo_market_insights.MetricType
	1,  // 1: geo_market_insights.AggregatesRequest.group_by:type_name -> geo_market_insights.GroupBy
	13, // 2: geo_market_insights.AggregatesRequest.locations:type_name -> geo_market_insights.Locations
	6,  // 3: geo_market_insights.AggregatesResponse.aggregates:type_name -> geo_market_insights.Aggregates
	14, // 4: geo_market_insights.AggregatesResponse.pagination:type_name -> geo_market_insights.Pagination
	1,  // 5: geo_market_insights.PriceComparisonRequest.group_by:type_name -> geo_market_insights.GroupBy
	2,  // 6: geo_market_insights.PriceComparisonRequest.sort_by:type_name -> geo_market_insights.SortBy
	3,  // 7: geo_market_insights.PriceComparisonRequest.order:type_name -> geo_market_insights.Order
	12, // 8: geo_market_insights.PriceComparisonResponse.comparisons:type_name -> geo_market_insights.Comparisons
	14, // 9: geo_market_insights.PriceComparisonResponse.pagination:type_name -> geo_market_insights.Pagination
	11, // 10: geo_market_insights.ByLocationResponse.stats:type_name -> geo_market_insights.Stats
	4,  // 11: geo_market_insights.GeoMarketInsightsService.Aggregates:input_type -> geo_market_insights.AggregatesRequest
	7,  // 12: geo_market_insights.GeoMarketInsightsService.PriceComparison:input_type -> geo_market_insights.PriceComparisonRequest
	9,  // 13: geo_market_insights.GeoMarketInsightsService.ByLocation:input_type -> geo_market_insights.ByLocationRequest
	5,  // 14: geo_market_insights.GeoMarketInsightsService.Aggregates:output_type -> geo_market_insights.AggregatesResponse
	8,  // 15: geo_market_insights.GeoMarketInsightsService.PriceComparison:output_type -> geo_market_insights.PriceComparisonResponse
	10, // 16: geo_market_insights.GeoMarketInsightsService.ByLocation:output_type -> geo_market_insights.ByLocationResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_geographic_maket_insights_proto_geo_market_insights_proto_init() }
func file_geographic_maket_insights_proto_geo_market_insights_proto_init() {
	if File_geographic_maket_insights_proto_geo_market_insights_proto != nil {
		return
	}
	file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[0].OneofWrappers = []any{}
	file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[3].OneofWrappers = []any{}
	file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[5].OneofWrappers = []any{}
	file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geographic_maket_insights_proto_geo_market_insights_proto_rawDesc), len(file_geographic_maket_insights_proto_geo_market_insights_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geographic_maket_insights_proto_geo_market_insights_proto_goTypes,
		DependencyIndexes: file_geographic_maket_insights_proto_geo_market_insights_proto_depIdxs,
		EnumInfos:         file_geographic_maket_insights_proto_geo_market_insights_proto_enumTypes,
		MessageInfos:      file_geographic_maket_insights_proto_geo_market_insights_proto_msgTypes,
	}.Build()
	File_geographic_maket_insights_proto_geo_market_insights_proto = out.File
	file_geographic_maket_insights_proto_geo_market_insights_proto_goTypes = nil
	file_geographic_maket_insights_proto_geo_market_insights_proto_depIdxs = nil
}
