// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: geographic-maket-insights/proto/geo-market-insights.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoMarketInsightsService_Aggregates_FullMethodName      = "/geo_market_insights.GeoMarketInsightsService/Aggregates"
	GeoMarketInsightsService_PriceComparison_FullMethodName = "/geo_market_insights.GeoMarketInsightsService/PriceComparison"
	GeoMarketInsightsService_ByLocation_FullMethodName      = "/geo_market_insights.GeoMarketInsightsService/ByLocation"
)

// GeoMarketInsightsServiceClient is the client API for GeoMarketInsightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoMarketInsightsServiceClient interface {
	Aggregates(ctx context.Context, in *AggregatesRequest, opts ...grpc.CallOption) (*AggregatesResponse, error)
	PriceComparison(ctx context.Context, in *PriceComparisonRequest, opts ...grpc.CallOption) (*PriceComparisonResponse, error)
	ByLocation(ctx context.Context, in *ByLocationRequest, opts ...grpc.CallOption) (*ByLocationResponse, error)
}

type geoMarketInsightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoMarketInsightsServiceClient(cc grpc.ClientConnInterface) GeoMarketInsightsServiceClient {
	return &geoMarketInsightsServiceClient{cc}
}

func (c *geoMarketInsightsServiceClient) Aggregates(ctx context.Context, in *AggregatesRequest, opts ...grpc.CallOption) (*AggregatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregatesResponse)
	err := c.cc.Invoke(ctx, GeoMarketInsightsService_Aggregates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoMarketInsightsServiceClient) PriceComparison(ctx context.Context, in *PriceComparisonRequest, opts ...grpc.CallOption) (*PriceComparisonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceComparisonResponse)
	err := c.cc.Invoke(ctx, GeoMarketInsightsService_PriceComparison_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoMarketInsightsServiceClient) ByLocation(ctx context.Context, in *ByLocationRequest, opts ...grpc.CallOption) (*ByLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ByLocationResponse)
	err := c.cc.Invoke(ctx, GeoMarketInsightsService_ByLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoMarketInsightsServiceServer is the server API for GeoMarketInsightsService service.
// All implementations must embed UnimplementedGeoMarketInsightsServiceServer
// for forward compatibility.
type GeoMarketInsightsServiceServer interface {
	Aggregates(context.Context, *AggregatesRequest) (*AggregatesResponse, error)
	PriceComparison(context.Context, *PriceComparisonRequest) (*PriceComparisonResponse, error)
	ByLocation(context.Context, *ByLocationRequest) (*ByLocationResponse, error)
	mustEmbedUnimplementedGeoMarketInsightsServiceServer()
}

// UnimplementedGeoMarketInsightsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoMarketInsightsServiceServer struct{}

func (UnimplementedGeoMarketInsightsServiceServer) Aggregates(context.Context, *AggregatesRequest) (*AggregatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Aggregates not implemented")
}
func (UnimplementedGeoMarketInsightsServiceServer) PriceComparison(context.Context, *PriceComparisonRequest) (*PriceComparisonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PriceComparison not implemented")
}
func (UnimplementedGeoMarketInsightsServiceServer) ByLocation(context.Context, *ByLocationRequest) (*ByLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ByLocation not implemented")
}
func (UnimplementedGeoMarketInsightsServiceServer) mustEmbedUnimplementedGeoMarketInsightsServiceServer() {
}
func (UnimplementedGeoMarketInsightsServiceServer) testEmbeddedByValue() {}

// UnsafeGeoMarketInsightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoMarketInsightsServiceServer will
// result in compilation errors.
type UnsafeGeoMarketInsightsServiceServer interface {
	mustEmbedUnimplementedGeoMarketInsightsServiceServer()
}

func RegisterGeoMarketInsightsServiceServer(s grpc.ServiceRegistrar, srv GeoMarketInsightsServiceServer) {
	// If the following call panics, it indicates UnimplementedGeoMarketInsightsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoMarketInsightsService_ServiceDesc, srv)
}

func _GeoMarketInsightsService_Aggregates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoMarketInsightsServiceServer).Aggregates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoMarketInsightsService_Aggregates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoMarketInsightsServiceServer).Aggregates(ctx, req.(*AggregatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoMarketInsightsService_PriceComparison_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceComparisonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoMarketInsightsServiceServer).PriceComparison(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoMarketInsightsService_PriceComparison_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoMarketInsightsServiceServer).PriceComparison(ctx, req.(*PriceComparisonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoMarketInsightsService_ByLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoMarketInsightsServiceServer).ByLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoMarketInsightsService_ByLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoMarketInsightsServiceServer).ByLocation(ctx, req.(*ByLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoMarketInsightsService_ServiceDesc is the grpc.ServiceDesc for GeoMarketInsightsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoMarketInsightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo_market_insights.GeoMarketInsightsService",
	HandlerType: (*GeoMarketInsightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Aggregates",
			Handler:    _GeoMarketInsightsService_Aggregates_Handler,
		},
		{
			MethodName: "PriceComparison",
			Handler:    _GeoMarketInsightsService_PriceComparison_Handler,
		},
		{
			MethodName: "ByLocation",
			Handler:    _GeoMarketInsightsService_ByLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geographic-maket-insights/proto/geo-market-insights.proto",
}
