// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: marketprice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AveragePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	YearFrom      int32                  `protobuf:"varint,3,opt,name=year_from,json=yearFrom,proto3" json:"year_from,omitempty"`
	YearTo        int32                  `protobuf:"varint,4,opt,name=year_to,json=yearTo,proto3" json:"year_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AveragePriceRequest) Reset() {
	*x = AveragePriceRequest{}
	mi := &file_marketprice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AveragePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AveragePriceRequest) ProtoMessage() {}

func (x *AveragePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketprice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AveragePriceRequest.ProtoReflect.Descriptor instead.
func (*AveragePriceRequest) Descriptor() ([]byte, []int) {
	return file_marketprice_proto_rawDescGZIP(), []int{0}
}

func (x *AveragePriceRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *AveragePriceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AveragePriceRequest) GetYearFrom() int32 {
	if x != nil {
		return x.YearFrom
	}
	return 0
}

func (x *AveragePriceRequest) GetYearTo() int32 {
	if x != nil {
		return x.YearTo
	}
	return 0
}

type AveragePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	AveragePrice  float64                `protobuf:"fixed64,3,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	ListingCount  int32                  `protobuf:"varint,6,opt,name=listing_count,json=listingCount,proto3" json:"listing_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AveragePriceResponse) Reset() {
	*x = AveragePriceResponse{}
	mi := &file_marketprice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AveragePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AveragePriceResponse) ProtoMessage() {}

func (x *AveragePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketprice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AveragePriceResponse.ProtoReflect.Descriptor instead.
func (*AveragePriceResponse) Descriptor() ([]byte, []int) {
	return file_marketprice_proto_rawDescGZIP(), []int{1}
}

func (x *AveragePriceResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *AveragePriceResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AveragePriceResponse) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *AveragePriceResponse) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *AveragePriceResponse) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *AveragePriceResponse) GetListingCount() int32 {
	if x != nil {
		return x.ListingCount
	}
	return 0
}

var File_marketprice_proto protoreflect.FileDescriptor

const file_marketprice_proto_rawDesc = "" +
	"\n" +
	"\x11marketprice.proto\x12\vmarketprice\"w\n" +
	"\x13AveragePriceRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\tyear_from\x18\x03 \x01(\x05R\byearFrom\x12\x17\n" +
	"\ayear_to\x18\x04 \x01(\x05R\x06yearTo\"\xc6\x01\n" +
	"\x14AveragePriceResponse\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\raverage_price\x18\x03 \x01(\x01R\faveragePrice\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12#\n" +
	"\rlisting_count\x18\x06 \x01(\x05R\flistingCount2r\n" +
	"\x12MarketPriceService\x12\\\n" +
	"\x15GetAverageMarketPrice\x12 .marketprice.AveragePriceRequest\x1a!.marketprice.AveragePriceResponseB\tZ\a./protob\x06proto3"

var (
	file_marketprice_proto_rawDescOnce sync.Once
	file_marketprice_proto_rawDescData []byte
)

func file_marketprice_proto_rawDescGZIP() []byte {
	file_marketprice_proto_rawDescOnce.Do(func() {
		file_marketprice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketprice_proto_rawDesc), len(file_marketprice_proto_rawDesc)))
	})
	return file_marketprice_proto_rawDescData
}

var file_marketprice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_marketprice_proto_goTypes = []any{
	(*AveragePriceRequest)(nil),  // 0: marketprice.AveragePriceRequest
	(*AveragePriceResponse)(nil), // 1: marketprice.AveragePriceResponse
}
var file_marketprice_proto_depIdxs = []int32{
	0, // 0: marketprice.MarketPriceService.GetAverageMarketPrice:input_type -> marketprice.AveragePriceRequest
	1, // 1: marketprice.MarketPriceService.GetAverageMarketPrice:output_type -> marketprice.AveragePriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketprice_proto_init() }
func file_marketprice_proto_init() {
	if File_marketprice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketprice_proto_rawDesc), len(file_marketprice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketprice_proto_goTypes,
		DependencyIndexes: file_marketprice_proto_depIdxs,
		MessageInfos:      file_marketprice_proto_msgTypes,
	}.Build()
	File_marketprice_proto = out.File
	file_marketprice_proto_goTypes = nil
	file_marketprice_proto_depIdxs = nil
}
