// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: listing/proto/listing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	shared "services/shared"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListingService_GetListingDetails_FullMethodName     = "/listing.ListingService/GetListingDetails"
	ListingService_GetListingSummary_FullMethodName     = "/listing.ListingService/GetListingSummary"
	ListingService_CompareListings_FullMethodName       = "/listing.ListingService/CompareListings"
	ListingService_CheckListingOwnership_FullMethodName = "/listing.ListingService/CheckListingOwnership"
)

// ListingServiceClient is the client API for ListingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListingServiceClient interface {
	// Get detailed information about a specific car listing by its ID.
	GetListingDetails(ctx context.Context, in *ListingDetailsRequest, opts ...grpc.CallOption) (*ListingDetailsResponse, error)
	// Get summarized information about a specific car listing by its ID, suitable for search results.
	GetListingSummary(ctx context.Context, in *ListingDetailsRequest, opts ...grpc.CallOption) (*shared.ListingSummary, error)
	// Compare multiple car listings by their IDs to see their details side by side.
	CompareListings(ctx context.Context, in *CompareListingsRequest, opts ...grpc.CallOption) (*CompareListingsResponse, error)
	// Checks if a listing with the given ID exists and belongs to a seller.
	CheckListingOwnership(ctx context.Context, in *CheckListingOwnershipRequest, opts ...grpc.CallOption) (*CheckListingOwnershipResponse, error)
}

type listingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListingServiceClient(cc grpc.ClientConnInterface) ListingServiceClient {
	return &listingServiceClient{cc}
}

func (c *listingServiceClient) GetListingDetails(ctx context.Context, in *ListingDetailsRequest, opts ...grpc.CallOption) (*ListingDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingDetailsResponse)
	err := c.cc.Invoke(ctx, ListingService_GetListingDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) GetListingSummary(ctx context.Context, in *ListingDetailsRequest, opts ...grpc.CallOption) (*shared.ListingSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(shared.ListingSummary)
	err := c.cc.Invoke(ctx, ListingService_GetListingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) CompareListings(ctx context.Context, in *CompareListingsRequest, opts ...grpc.CallOption) (*CompareListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareListingsResponse)
	err := c.cc.Invoke(ctx, ListingService_CompareListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingServiceClient) CheckListingOwnership(ctx context.Context, in *CheckListingOwnershipRequest, opts ...grpc.CallOption) (*CheckListingOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckListingOwnershipResponse)
	err := c.cc.Invoke(ctx, ListingService_CheckListingOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListingServiceServer is the server API for ListingService service.
// All implementations must embed UnimplementedListingServiceServer
// for forward compatibility.
type ListingServiceServer interface {
	// Get detailed information about a specific car listing by its ID.
	GetListingDetails(context.Context, *ListingDetailsRequest) (*ListingDetailsResponse, error)
	// Get summarized information about a specific car listing by its ID, suitable for search results.
	GetListingSummary(context.Context, *ListingDetailsRequest) (*shared.ListingSummary, error)
	// Compare multiple car listings by their IDs to see their details side by side.
	CompareListings(context.Context, *CompareListingsRequest) (*CompareListingsResponse, error)
	// Checks if a listing with the given ID exists and belongs to a seller.
	CheckListingOwnership(context.Context, *CheckListingOwnershipRequest) (*CheckListingOwnershipResponse, error)
	mustEmbedUnimplementedListingServiceServer()
}

// UnimplementedListingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListingServiceServer struct{}

func (UnimplementedListingServiceServer) GetListingDetails(context.Context, *ListingDetailsRequest) (*ListingDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListingDetails not implemented")
}
func (UnimplementedListingServiceServer) GetListingSummary(context.Context, *ListingDetailsRequest) (*shared.ListingSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListingSummary not implemented")
}
func (UnimplementedListingServiceServer) CompareListings(context.Context, *CompareListingsRequest) (*CompareListingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareListings not implemented")
}
func (UnimplementedListingServiceServer) CheckListingOwnership(context.Context, *CheckListingOwnershipRequest) (*CheckListingOwnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckListingOwnership not implemented")
}
func (UnimplementedListingServiceServer) mustEmbedUnimplementedListingServiceServer() {}
func (UnimplementedListingServiceServer) testEmbeddedByValue()                        {}

// UnsafeListingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListingServiceServer will
// result in compilation errors.
type UnsafeListingServiceServer interface {
	mustEmbedUnimplementedListingServiceServer()
}

func RegisterListingServiceServer(s grpc.ServiceRegistrar, srv ListingServiceServer) {
	// If the following call panics, it indicates UnimplementedListingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListingService_ServiceDesc, srv)
}

func _ListingService_GetListingDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListingDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_GetListingDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListingDetails(ctx, req.(*ListingDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_GetListingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).GetListingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_GetListingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).GetListingSummary(ctx, req.(*ListingDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_CompareListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).CompareListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_CompareListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).CompareListings(ctx, req.(*CompareListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListingService_CheckListingOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckListingOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingServiceServer).CheckListingOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListingService_CheckListingOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingServiceServer).CheckListingOwnership(ctx, req.(*CheckListingOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListingService_ServiceDesc is the grpc.ServiceDesc for ListingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listing.ListingService",
	HandlerType: (*ListingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListingDetails",
			Handler:    _ListingService_GetListingDetails_Handler,
		},
		{
			MethodName: "GetListingSummary",
			Handler:    _ListingService_GetListingSummary_Handler,
		},
		{
			MethodName: "CompareListings",
			Handler:    _ListingService_CompareListings_Handler,
		},
		{
			MethodName: "CheckListingOwnership",
			Handler:    _ListingService_CheckListingOwnership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "listing/proto/listing.proto",
}
