// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: listing/proto/listing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	shared "services/shared"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsRequest) Reset() {
	*x = ListingDetailsRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsRequest) ProtoMessage() {}

func (x *ListingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsRequest.ProtoReflect.Descriptor instead.
func (*ListingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{0}
}

func (x *ListingDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListingSummariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingSummariesRequest) Reset() {
	*x = ListingSummariesRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingSummariesRequest) ProtoMessage() {}

func (x *ListingSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingSummariesRequest.ProtoReflect.Descriptor instead.
func (*ListingSummariesRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{1}
}

func (x *ListingSummariesRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListingSummariesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Listings      []*shared.ListingSummary `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingSummariesResponse) Reset() {
	*x = ListingSummariesResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingSummariesResponse) ProtoMessage() {}

func (x *ListingSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingSummariesResponse.ProtoReflect.Descriptor instead.
func (*ListingSummariesResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ListingSummariesResponse) GetListings() []*shared.ListingSummary {
	if x != nil {
		return x.Listings
	}
	return nil
}

type ListingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	State         string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	FuelType      string                 `protobuf:"bytes,11,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Trim          string                 `protobuf:"bytes,12,opt,name=trim,proto3" json:"trim,omitempty"`
	Transmission  string                 `protobuf:"bytes,13,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Color         string                 `protobuf:"bytes,14,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,15,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	Description   string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	ListedAt      string                 `protobuf:"bytes,17,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	Images        []string               `protobuf:"bytes,18,rep,name=images,proto3" json:"images,omitempty"`
	IsSold        bool                   `protobuf:"varint,19,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsResponse) Reset() {
	*x = ListingDetailsResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsResponse) ProtoMessage() {}

func (x *ListingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsResponse.ProtoReflect.Descriptor instead.
func (*ListingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{3}
}

func (x *ListingDetailsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingDetailsResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingDetailsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingDetailsResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingDetailsResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingDetailsResponse) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingDetailsResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListingDetailsResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ListingDetailsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListingDetailsResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListingDetailsResponse) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *ListingDetailsResponse) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *ListingDetailsResponse) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *ListingDetailsResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ListingDetailsResponse) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *ListingDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingDetailsResponse) GetListedAt() string {
	if x != nil {
		return x.ListedAt
	}
	return ""
}

func (x *ListingDetailsResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ListingDetailsResponse) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	State         string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	FuelType      string                 `protobuf:"bytes,11,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	BodyClass     string                 `protobuf:"bytes,12,opt,name=body_class,json=bodyClass,proto3" json:"body_class,omitempty"`
	DriveType     string                 `protobuf:"bytes,13,opt,name=drive_type,json=driveType,proto3" json:"drive_type,omitempty"`
	Transmission  string                 `protobuf:"bytes,14,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Trim          string                 `protobuf:"bytes,15,opt,name=trim,proto3" json:"trim,omitempty"`
	Color         string                 `protobuf:"bytes,16,opt,name=color,proto3" json:"color,omitempty"`
	DealerId      int64                  `protobuf:"varint,17,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	IsNew         bool                   `protobuf:"varint,18,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsSold        bool                   `protobuf:"varint,19,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateListingRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CreateListingRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CreateListingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateListingRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *CreateListingRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateListingRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateListingRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateListingRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateListingRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *CreateListingRequest) GetBodyClass() string {
	if x != nil {
		return x.BodyClass
	}
	return ""
}

func (x *CreateListingRequest) GetDriveType() string {
	if x != nil {
		return x.DriveType
	}
	return ""
}

func (x *CreateListingRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *CreateListingRequest) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *CreateListingRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateListingRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

func (x *CreateListingRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateListingRequest) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

type UpdateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`
	Make          string                 `protobuf:"bytes,3,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,7,opt,name=mileage,proto3" json:"mileage,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	State         string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	FuelType      string                 `protobuf:"bytes,12,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	BodyClass     string                 `protobuf:"bytes,13,opt,name=body_class,json=bodyClass,proto3" json:"body_class,omitempty"`
	DriveType     string                 `protobuf:"bytes,14,opt,name=drive_type,json=driveType,proto3" json:"drive_type,omitempty"`
	Transmission  string                 `protobuf:"bytes,15,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Trim          string                 `protobuf:"bytes,16,opt,name=trim,proto3" json:"trim,omitempty"`
	Color         string                 `protobuf:"bytes,17,opt,name=color,proto3" json:"color,omitempty"`
	DealerId      int64                  `protobuf:"varint,18,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	IsNew         bool                   `protobuf:"varint,19,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListingRequest) Reset() {
	*x = UpdateListingRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingRequest) ProtoMessage() {}

func (x *UpdateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingRequest.ProtoReflect.Descriptor instead.
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateListingRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *UpdateListingRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *UpdateListingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateListingRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateListingRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *UpdateListingRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateListingRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateListingRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateListingRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateListingRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *UpdateListingRequest) GetBodyClass() string {
	if x != nil {
		return x.BodyClass
	}
	return ""
}

func (x *UpdateListingRequest) GetDriveType() string {
	if x != nil {
		return x.DriveType
	}
	return ""
}

func (x *UpdateListingRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *UpdateListingRequest) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *UpdateListingRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateListingRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

func (x *UpdateListingRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type SetListingSoldStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DealerId      int64                  `protobuf:"varint,2,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	IsSold        bool                   `protobuf:"varint,3,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetListingSoldStatusRequest) Reset() {
	*x = SetListingSoldStatusRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetListingSoldStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetListingSoldStatusRequest) ProtoMessage() {}

func (x *SetListingSoldStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetListingSoldStatusRequest.ProtoReflect.Descriptor instead.
func (*SetListingSoldStatusRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{6}
}

func (x *SetListingSoldStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetListingSoldStatusRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

func (x *SetListingSoldStatusRequest) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

type DeleteListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DealerId      int64                  `protobuf:"varint,2,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingRequest) Reset() {
	*x = DeleteListingRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingRequest) ProtoMessage() {}

func (x *DeleteListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteListingRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

type DeleteListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingResponse) Reset() {
	*x = DeleteListingResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingResponse) ProtoMessage() {}

func (x *DeleteListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingResponse.ProtoReflect.Descriptor instead.
func (*DeleteListingResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteListingResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type CompareListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsRequest) Reset() {
	*x = CompareListingsRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsRequest) ProtoMessage() {}

func (x *CompareListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsRequest.ProtoReflect.Descriptor instead.
func (*CompareListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{9}
}

func (x *CompareListingsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CompareListingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Listings      []*ListingDetailsResponse `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsResponse) Reset() {
	*x = CompareListingsResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsResponse) ProtoMessage() {}

func (x *CompareListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsResponse.ProtoReflect.Descriptor instead.
func (*CompareListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{10}
}

func (x *CompareListingsResponse) GetListings() []*ListingDetailsResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

type CheckListingOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	DealerId      int64                  `protobuf:"varint,2,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOwnershipRequest) Reset() {
	*x = CheckListingOwnershipRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOwnershipRequest) ProtoMessage() {}

func (x *CheckListingOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOwnershipRequest.ProtoReflect.Descriptor instead.
func (*CheckListingOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{11}
}

func (x *CheckListingOwnershipRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *CheckListingOwnershipRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

type CheckListingOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOwner       bool                   `protobuf:"varint,1,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOwnershipResponse) Reset() {
	*x = CheckListingOwnershipResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOwnershipResponse) ProtoMessage() {}

func (x *CheckListingOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOwnershipResponse.ProtoReflect.Descriptor instead.
func (*CheckListingOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{12}
}

func (x *CheckListingOwnershipResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type CheckListingOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOpenRequest) Reset() {
	*x = CheckListingOpenRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOpenRequest) ProtoMessage() {}

func (x *CheckListingOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOpenRequest.ProtoReflect.Descriptor instead.
func (*CheckListingOpenRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{13}
}

func (x *CheckListingOpenRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

type CheckListingOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	DealerId      int64                  `protobuf:"varint,2,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOpenResponse) Reset() {
	*x = CheckListingOpenResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOpenResponse) ProtoMessage() {}

func (x *CheckListingOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOpenResponse.ProtoReflect.Descriptor instead.
func (*CheckListingOpenResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{14}
}

func (x *CheckListingOpenResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *CheckListingOpenResponse) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

var File_listing_proto_listing_proto protoreflect.FileDescriptor

const file_listing_proto_listing_proto_rawDesc = "" +
	"\n" +
	"\x1blisting/proto/listing.proto\x12\alisting\x1a\x13shared/shared.proto\"'\n" +
	"\x15ListingDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"+\n" +
	"\x17ListingSummariesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"N\n" +
	"\x18ListingSummariesResponse\x122\n" +
	"\blistings\x18\x01 \x03(\v2\x16.shared.ListingSummaryR\blistings\"\xf2\x03\n" +
	"\x16ListingDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1b\n" +
	"\tfuel_type\x18\v \x01(\tR\bfuelType\x12\x12\n" +
	"\x04trim\x18\f \x01(\tR\x04trim\x12\"\n" +
	"\ftransmission\x18\r \x01(\tR\ftransmission\x12\x14\n" +
	"\x05color\x18\x0e \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\x0f \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x12\x1b\n" +
	"\tlisted_at\x18\x11 \x01(\tR\blistedAt\x12\x16\n" +
	"\x06images\x18\x12 \x03(\tR\x06images\x12\x17\n" +
	"\ais_sold\x18\x13 \x01(\bR\x06isSold\"\xec\x03\n" +
	"\x14CreateListingRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1b\n" +
	"\tfuel_type\x18\v \x01(\tR\bfuelType\x12\x1d\n" +
	"\n" +
	"body_class\x18\f \x01(\tR\tbodyClass\x12\x1d\n" +
	"\n" +
	"drive_type\x18\r \x01(\tR\tdriveType\x12\"\n" +
	"\ftransmission\x18\x0e \x01(\tR\ftransmission\x12\x12\n" +
	"\x04trim\x18\x0f \x01(\tR\x04trim\x12\x14\n" +
	"\x05color\x18\x10 \x01(\tR\x05color\x12\x1b\n" +
	"\tdealer_id\x18\x11 \x01(\x03R\bdealerId\x12\x15\n" +
	"\x06is_new\x18\x12 \x01(\bR\x05isNew\x12\x17\n" +
	"\ais_sold\x18\x13 \x01(\bR\x06isSold\"\xe3\x03\n" +
	"\x14UpdateListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12\x12\n" +
	"\x04make\x18\x03 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\a \x01(\x05R\amileage\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\t \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1b\n" +
	"\tfuel_type\x18\f \x01(\tR\bfuelType\x12\x1d\n" +
	"\n" +
	"body_class\x18\r \x01(\tR\tbodyClass\x12\x1d\n" +
	"\n" +
	"drive_type\x18\x0e \x01(\tR\tdriveType\x12\"\n" +
	"\ftransmission\x18\x0f \x01(\tR\ftransmission\x12\x12\n" +
	"\x04trim\x18\x10 \x01(\tR\x04trim\x12\x14\n" +
	"\x05color\x18\x11 \x01(\tR\x05color\x12\x1b\n" +
	"\tdealer_id\x18\x12 \x01(\x03R\bdealerId\x12\x15\n" +
	"\x06is_new\x18\x13 \x01(\bR\x05isNew\"c\n" +
	"\x1bSetListingSoldStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdealer_id\x18\x02 \x01(\x03R\bdealerId\x12\x17\n" +
	"\ais_sold\x18\x03 \x01(\bR\x06isSold\"C\n" +
	"\x14DeleteListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdealer_id\x18\x02 \x01(\x03R\bdealerId\"1\n" +
	"\x15DeleteListingResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"*\n" +
	"\x16CompareListingsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"V\n" +
	"\x17CompareListingsResponse\x12;\n" +
	"\blistings\x18\x01 \x03(\v2\x1f.listing.ListingDetailsResponseR\blistings\"Z\n" +
	"\x1cCheckListingOwnershipRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\x12\x1b\n" +
	"\tdealer_id\x18\x02 \x01(\x03R\bdealerId\":\n" +
	"\x1dCheckListingOwnershipResponse\x12\x19\n" +
	"\bis_owner\x18\x01 \x01(\bR\aisOwner\"8\n" +
	"\x17CheckListingOpenRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\"P\n" +
	"\x18CheckListingOpenResponse\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\x12\x1b\n" +
	"\tdealer_id\x18\x02 \x01(\x03R\bdealerId2\xf7\x06\n" +
	"\x0eListingService\x12T\n" +
	"\x11GetListingDetails\x12\x1e.listing.ListingDetailsRequest\x1a\x1f.listing.ListingDetailsResponse\x12K\n" +
	"\x11GetListingSummary\x12\x1e.listing.ListingDetailsRequest\x1a\x16.shared.ListingSummary\x12Z\n" +
	"\x13GetListingSummaries\x12 .listing.ListingSummariesRequest\x1a!.listing.ListingSummariesResponse\x12O\n" +
	"\rCreateListing\x12\x1d.listing.CreateListingRequest\x1a\x1f.listing.ListingDetailsResponse\x12O\n" +
	"\rUpdateListing\x12\x1d.listing.UpdateListingRequest\x1a\x1f.listing.ListingDetailsResponse\x12]\n" +
	"\x14SetListingSoldStatus\x12$.listing.SetListingSoldStatusRequest\x1a\x1f.listing.ListingDetailsResponse\x12N\n" +
	"\rDeleteListing\x12\x1d.listing.DeleteListingRequest\x1a\x1e.listing.DeleteListingResponse\x12T\n" +
	"\x0fCompareListings\x12\x1f.listing.CompareListingsRequest\x1a .listing.CompareListingsResponse\x12f\n" +
	"\x15CheckListingOwnership\x12%.listing.CheckListingOwnershipRequest\x1a&.listing.CheckListingOwnershipResponse\x12W\n" +
	"\x10CheckListingOpen\x12 .listing.CheckListingOpenRequest\x1a!.listing.CheckListingOpenResponseB\x18Z\x16services/listing/protob\x06proto3"

var (
	file_listing_proto_listing_proto_rawDescOnce sync.Once
	file_listing_proto_listing_proto_rawDescData []byte
)

func file_listing_proto_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_listing_proto_rawDesc), len(file_listing_proto_listing_proto_rawDesc)))
	})
	return file_listing_proto_listing_proto_rawDescData
}

var file_listing_proto_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_listing_proto_listing_proto_goTypes = []any{
	(*ListingDetailsRequest)(nil),         // 0: listing.ListingDetailsRequest
	(*ListingSummariesRequest)(nil),       // 1: listing.ListingSummariesRequest
	(*ListingSummariesResponse)(nil),      // 2: listing.ListingSummariesResponse
	(*ListingDetailsResponse)(nil),        // 3: listing.ListingDetailsResponse
	(*CreateListingRequest)(nil),          // 4: listing.CreateListingRequest
	(*UpdateListingRequest)(nil),          // 5: listing.UpdateListingRequest
	(*SetListingSoldStatusRequest)(nil),   // 6: listing.SetListingSoldStatusRequest
	(*DeleteListingRequest)(nil),          // 7: listing.DeleteListingRequest
	(*DeleteListingResponse)(nil),         // 8: listing.DeleteListingResponse
	(*CompareListingsRequest)(nil),        // 9: listing.CompareListingsRequest
	(*CompareListingsResponse)(nil),       // 10: listing.CompareListingsResponse
	(*CheckListingOwnershipRequest)(nil),  // 11: listing.CheckListingOwnershipRequest
	(*CheckListingOwnershipResponse)(nil), // 12: listing.CheckListingOwnershipResponse
	(*CheckListingOpenRequest)(nil),       // 13: listing.CheckListingOpenRequest
	(*CheckListingOpenResponse)(nil),      // 14: listing.CheckListingOpenResponse
	(*shared.ListingSummary)(nil),         // 15: shared.ListingSummary
}
var file_listing_proto_listing_proto_depIdxs = []int32{
	15, // 0: listing.ListingSummariesResponse.listings:type_name -> shared.ListingSummary
	3,  // 1: listing.CompareListingsResponse.listings:type_name -> listing.ListingDetailsResponse
	0,  // 2: listing.ListingService.GetListingDetails:input_type -> listing.ListingDetailsRequest
	0,  // 3: listing.ListingService.GetListingSummary:input_type -> listing.ListingDetailsRequest
	1,  // 4: listing.ListingService.GetListingSummaries:input_type -> listing.ListingSummariesRequest
	4,  // 5: listing.ListingService.CreateListing:input_type -> listing.CreateListingRequest
	5,  // 6: listing.ListingService.UpdateListing:input_type -> listing.UpdateListingRequest
	6,  // 7: listing.ListingService.SetListingSoldStatus:input_type -> listing.SetListingSoldStatusRequest
	7,  // 8: listing.ListingService.DeleteListing:input_type -> listing.DeleteListingRequest
	9,  // 9: listing.ListingService.CompareListings:input_type -> listing.CompareListingsRequest
	11, // 10: listing.ListingService.CheckListingOwnership:input_type -> listing.CheckListingOwnershipRequest
	13, // 11: listing.ListingService.CheckListingOpen:input_type -> listing.CheckListingOpenRequest
	3,  // 12: listing.ListingService.GetListingDetails:output_type -> listing.ListingDetailsResponse
	15, // 13: listing.ListingService.GetListingSummary:output_type -> shared.ListingSummary
	2,  // 14: listing.ListingService.GetListingSummaries:output_type -> listing.ListingSummariesResponse
	3,  // 15: listing.ListingService.CreateListing:output_type -> listing.ListingDetailsResponse
	3,  // 16: listing.ListingService.UpdateListing:output_type -> listing.ListingDetailsResponse
	3,  // 17: listing.ListingService.SetListingSoldStatus:output_type -> listing.ListingDetailsResponse
	8,  // 18: listing.ListingService.DeleteListing:output_type -> listing.DeleteListingResponse
	10, // 19: listing.ListingService.CompareListings:output_type -> listing.CompareListingsResponse
	12, // 20: listing.ListingService.CheckListingOwnership:output_type -> listing.CheckListingOwnershipResponse
	14, // 21: listing.ListingService.CheckListingOpen:output_type -> listing.CheckListingOpenResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_listing_proto_listing_proto_init() }
func file_listing_proto_listing_proto_init() {
	if File_listing_proto_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_listing_proto_rawDesc), len(file_listing_proto_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_proto_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_listing_proto_depIdxs,
		MessageInfos:      file_listing_proto_listing_proto_msgTypes,
	}.Build()
	File_listing_proto_listing_proto = out.File
	file_listing_proto_listing_proto_goTypes = nil
	file_listing_proto_listing_proto_depIdxs = nil
}
