// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: listing/proto/listing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	shared "services/shared"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsRequest) Reset() {
	*x = ListingDetailsRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsRequest) ProtoMessage() {}

func (x *ListingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsRequest.ProtoReflect.Descriptor instead.
func (*ListingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{0}
}

func (x *ListingDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	State         string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	FuelType      string                 `protobuf:"bytes,11,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Trim          string                 `protobuf:"bytes,12,opt,name=trim,proto3" json:"trim,omitempty"`
	Transmission  string                 `protobuf:"bytes,13,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Color         string                 `protobuf:"bytes,14,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,15,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	Description   string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	ListedAt      string                 `protobuf:"bytes,17,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	Images        []string               `protobuf:"bytes,18,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsResponse) Reset() {
	*x = ListingDetailsResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsResponse) ProtoMessage() {}

func (x *ListingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsResponse.ProtoReflect.Descriptor instead.
func (*ListingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{1}
}

func (x *ListingDetailsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingDetailsResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingDetailsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingDetailsResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingDetailsResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingDetailsResponse) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingDetailsResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListingDetailsResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ListingDetailsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListingDetailsResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListingDetailsResponse) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *ListingDetailsResponse) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *ListingDetailsResponse) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *ListingDetailsResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ListingDetailsResponse) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *ListingDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingDetailsResponse) GetListedAt() string {
	if x != nil {
		return x.ListedAt
	}
	return ""
}

func (x *ListingDetailsResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CompareListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsRequest) Reset() {
	*x = CompareListingsRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsRequest) ProtoMessage() {}

func (x *CompareListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsRequest.ProtoReflect.Descriptor instead.
func (*CompareListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{2}
}

func (x *CompareListingsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CompareListingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Listings      []*ListingDetailsResponse `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsResponse) Reset() {
	*x = CompareListingsResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsResponse) ProtoMessage() {}

func (x *CompareListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsResponse.ProtoReflect.Descriptor instead.
func (*CompareListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{3}
}

func (x *CompareListingsResponse) GetListings() []*ListingDetailsResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

type CheckListingOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	DealerId      int64                  `protobuf:"varint,2,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOwnershipRequest) Reset() {
	*x = CheckListingOwnershipRequest{}
	mi := &file_listing_proto_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOwnershipRequest) ProtoMessage() {}

func (x *CheckListingOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOwnershipRequest.ProtoReflect.Descriptor instead.
func (*CheckListingOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{4}
}

func (x *CheckListingOwnershipRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *CheckListingOwnershipRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

type CheckListingOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOwner       bool                   `protobuf:"varint,1,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOwnershipResponse) Reset() {
	*x = CheckListingOwnershipResponse{}
	mi := &file_listing_proto_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOwnershipResponse) ProtoMessage() {}

func (x *CheckListingOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOwnershipResponse.ProtoReflect.Descriptor instead.
func (*CheckListingOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_listing_proto_rawDescGZIP(), []int{5}
}

func (x *CheckListingOwnershipResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

var File_listing_proto_listing_proto protoreflect.FileDescriptor

const file_listing_proto_listing_proto_rawDesc = "" +
	"\n" +
	"\x1blisting/proto/listing.proto\x12\alisting\x1a\x13shared/shared.proto\"'\n" +
	"\x15ListingDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd9\x03\n" +
	"\x16ListingDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x1b\n" +
	"\tfuel_type\x18\v \x01(\tR\bfuelType\x12\x12\n" +
	"\x04trim\x18\f \x01(\tR\x04trim\x12\"\n" +
	"\ftransmission\x18\r \x01(\tR\ftransmission\x12\x14\n" +
	"\x05color\x18\x0e \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\x0f \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x12\x1b\n" +
	"\tlisted_at\x18\x11 \x01(\tR\blistedAt\x12\x16\n" +
	"\x06images\x18\x12 \x03(\tR\x06images\"*\n" +
	"\x16CompareListingsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"V\n" +
	"\x17CompareListingsResponse\x12;\n" +
	"\blistings\x18\x01 \x03(\v2\x1f.listing.ListingDetailsResponseR\blistings\"Z\n" +
	"\x1cCheckListingOwnershipRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\x12\x1b\n" +
	"\tdealer_id\x18\x02 \x01(\x03R\bdealerId\":\n" +
	"\x1dCheckListingOwnershipResponse\x12\x19\n" +
	"\bis_owner\x18\x01 \x01(\bR\aisOwner2\xf1\x02\n" +
	"\x0eListingService\x12T\n" +
	"\x11GetListingDetails\x12\x1e.listing.ListingDetailsRequest\x1a\x1f.listing.ListingDetailsResponse\x12K\n" +
	"\x11GetListingSummary\x12\x1e.listing.ListingDetailsRequest\x1a\x16.shared.ListingSummary\x12T\n" +
	"\x0fCompareListings\x12\x1f.listing.CompareListingsRequest\x1a .listing.CompareListingsResponse\x12f\n" +
	"\x15CheckListingOwnership\x12%.listing.CheckListingOwnershipRequest\x1a&.listing.CheckListingOwnershipResponseB\x18Z\x16services/listing/protob\x06proto3"

var (
	file_listing_proto_listing_proto_rawDescOnce sync.Once
	file_listing_proto_listing_proto_rawDescData []byte
)

func file_listing_proto_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_listing_proto_rawDesc), len(file_listing_proto_listing_proto_rawDesc)))
	})
	return file_listing_proto_listing_proto_rawDescData
}

var file_listing_proto_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_listing_proto_listing_proto_goTypes = []any{
	(*ListingDetailsRequest)(nil),         // 0: listing.ListingDetailsRequest
	(*ListingDetailsResponse)(nil),        // 1: listing.ListingDetailsResponse
	(*CompareListingsRequest)(nil),        // 2: listing.CompareListingsRequest
	(*CompareListingsResponse)(nil),       // 3: listing.CompareListingsResponse
	(*CheckListingOwnershipRequest)(nil),  // 4: listing.CheckListingOwnershipRequest
	(*CheckListingOwnershipResponse)(nil), // 5: listing.CheckListingOwnershipResponse
	(*shared.ListingSummary)(nil),         // 6: shared.ListingSummary
}
var file_listing_proto_listing_proto_depIdxs = []int32{
	1, // 0: listing.CompareListingsResponse.listings:type_name -> listing.ListingDetailsResponse
	0, // 1: listing.ListingService.GetListingDetails:input_type -> listing.ListingDetailsRequest
	0, // 2: listing.ListingService.GetListingSummary:input_type -> listing.ListingDetailsRequest
	2, // 3: listing.ListingService.CompareListings:input_type -> listing.CompareListingsRequest
	4, // 4: listing.ListingService.CheckListingOwnership:input_type -> listing.CheckListingOwnershipRequest
	1, // 5: listing.ListingService.GetListingDetails:output_type -> listing.ListingDetailsResponse
	6, // 6: listing.ListingService.GetListingSummary:output_type -> shared.ListingSummary
	3, // 7: listing.ListingService.CompareListings:output_type -> listing.CompareListingsResponse
	5, // 8: listing.ListingService.CheckListingOwnership:output_type -> listing.CheckListingOwnershipResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_listing_proto_listing_proto_init() }
func file_listing_proto_listing_proto_init() {
	if File_listing_proto_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_listing_proto_rawDesc), len(file_listing_proto_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_proto_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_listing_proto_depIdxs,
		MessageInfos:      file_listing_proto_listing_proto_msgTypes,
	}.Build()
	File_listing_proto_listing_proto = out.File
	file_listing_proto_listing_proto_goTypes = nil
	file_listing_proto_listing_proto_depIdxs = nil
}
