apiVersion: v1
kind: Secret
metadata:
  name: seller-secrets
type: Opaque
stringData:
  SELLER_DATABASE_URL: postgres://postgres:uma_password_forte_aqui@127.0.0.1:5432/seller_db?sslmode=disable
  SELLER_POSTGRES_DB: seller_db
  SELLER_POSTGRES_USER: postgres
  SELLER_POSTGRES_PASSWORD: uma_password_forte_aqui
  LISTING_DATABASE_URL: postgres://postgres:uma_password_forte_aqui@127.0.0.1:5432/listing_db?sslmode=disable
  SELLER_GRPC_PORT: "50057"