// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: auction/proto/auction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	SellerId      int64                  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	StartingPrice float64                `protobuf:"fixed64,4,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"`
	CurrentPrice  *float64               `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3,oneof" json:"current_price,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	WinnerUserId  *string                `protobuf:"bytes,8,opt,name=winner_user_id,json=winnerUserId,proto3,oneof" json:"winner_user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReserveMet    bool                   `protobuf:"varint,10,opt,name=reserve_met,json=reserveMet,proto3" json:"reserve_met,omitempty"`
	TotalBids     int32                  `protobuf:"varint,11,opt,name=total_bids,json=totalBids,proto3" json:"total_bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_auction_proto_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Auction) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *Auction) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *Auction) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Auction) GetStartingPrice() float64 {
	if x != nil {
		return x.StartingPrice
	}
	return 0
}

func (x *Auction) GetCurrentPrice() float64 {
	if x != nil && x.CurrentPrice != nil {
		return *x.CurrentPrice
	}
	return 0
}

func (x *Auction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Auction) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Auction) GetWinnerUserId() string {
	if x != nil && x.WinnerUserId != nil {
		return *x.WinnerUserId
	}
	return ""
}

func (x *Auction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Auction) GetReserveMet() bool {
	if x != nil {
		return x.ReserveMet
	}
	return false
}

func (x *Auction) GetTotalBids() int32 {
	if x != nil {
		return x.TotalBids
	}
	return 0
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	AuctionId     string                 `protobuf:"bytes,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidderId      string                 `protobuf:"bytes,3,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	BidAmount     float64                `protobuf:"fixed64,4,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_auction_proto_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{1}
}

func (x *Bid) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *Bid) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *Bid) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *Bid) GetBidAmount() float64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

func (x *Bid) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ListAuctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuctionsRequest) Reset() {
	*x = ListAuctionsRequest{}
	mi := &file_auction_proto_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuctionsRequest) ProtoMessage() {}

func (x *ListAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuctionsRequest.ProtoReflect.Descriptor instead.
func (*ListAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuctionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAuctionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuctionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAuctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*Auction             `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuctionsResponse) Reset() {
	*x = ListAuctionsResponse{}
	mi := &file_auction_proto_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuctionsResponse) ProtoMessage() {}

func (x *ListAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuctionsResponse.ProtoReflect.Descriptor instead.
func (*ListAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuctionsResponse) GetAuctions() []*Auction {
	if x != nil {
		return x.Auctions
	}
	return nil
}

func (x *ListAuctionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAuctionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuctionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	SellerId      int64                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	StartingPrice float64                `protobuf:"fixed64,3,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ReservePrice  *float64               `protobuf:"fixed64,5,opt,name=reserve_price,json=reservePrice,proto3,oneof" json:"reserve_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_auction_proto_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAuctionRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *CreateAuctionRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateAuctionRequest) GetStartingPrice() float64 {
	if x != nil {
		return x.StartingPrice
	}
	return 0
}

func (x *CreateAuctionRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateAuctionRequest) GetReservePrice() float64 {
	if x != nil && x.ReservePrice != nil {
		return *x.ReservePrice
	}
	return 0
}

type CreateAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auction       *Auction               `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionResponse) Reset() {
	*x = CreateAuctionResponse{}
	mi := &file_auction_proto_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionResponse) ProtoMessage() {}

func (x *CreateAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionResponse.ProtoReflect.Descriptor instead.
func (*CreateAuctionResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAuctionResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

type GetAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionRequest) Reset() {
	*x = GetAuctionRequest{}
	mi := &file_auction_proto_auction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionRequest) ProtoMessage() {}

func (x *GetAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuctionRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type GetAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auction       *Auction               `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionResponse) Reset() {
	*x = GetAuctionResponse{}
	mi := &file_auction_proto_auction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionResponse) ProtoMessage() {}

func (x *GetAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuctionResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

type DeleteAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuctionRequest) Reset() {
	*x = DeleteAuctionRequest{}
	mi := &file_auction_proto_auction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuctionRequest) ProtoMessage() {}

func (x *DeleteAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuctionRequest.ProtoReflect.Descriptor instead.
func (*DeleteAuctionRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAuctionRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *DeleteAuctionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuctionResponse) Reset() {
	*x = DeleteAuctionResponse{}
	mi := &file_auction_proto_auction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuctionResponse) ProtoMessage() {}

func (x *DeleteAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuctionResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuctionResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAuctionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidderId      string                 `protobuf:"bytes,2,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	BidAmount     float64                `protobuf:"fixed64,3,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_auction_proto_auction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{10}
}

func (x *PlaceBidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *PlaceBidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *PlaceBidRequest) GetBidAmount() float64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           *Bid                   `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_auction_proto_auction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{11}
}

func (x *PlaceBidResponse) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type GetAuctionBidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionBidsRequest) Reset() {
	*x = GetAuctionBidsRequest{}
	mi := &file_auction_proto_auction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionBidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionBidsRequest) ProtoMessage() {}

func (x *GetAuctionBidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionBidsRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionBidsRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{12}
}

func (x *GetAuctionBidsRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *GetAuctionBidsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuctionBidsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAuctionBidsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*Bid                 `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionBidsResponse) Reset() {
	*x = GetAuctionBidsResponse{}
	mi := &file_auction_proto_auction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionBidsResponse) ProtoMessage() {}

func (x *GetAuctionBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_auction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionBidsResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionBidsResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_auction_proto_rawDescGZIP(), []int{13}
}

func (x *GetAuctionBidsResponse) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetAuctionBidsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAuctionBidsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuctionBidsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_auction_proto_auction_proto protoreflect.FileDescriptor

const file_auction_proto_auction_proto_rawDesc = "" +
	"\n" +
	"\x1bauction/proto/auction.proto\x12\aauction\"\x97\x03\n" +
	"\aAuction\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\x12%\n" +
	"\x0estarting_price\x18\x04 \x01(\x01R\rstartingPrice\x12(\n" +
	"\rcurrent_price\x18\x05 \x01(\x01H\x00R\fcurrentPrice\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12)\n" +
	"\x0ewinner_user_id\x18\b \x01(\tH\x01R\fwinnerUserId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vreserve_met\x18\n" +
	" \x01(\bR\n" +
	"reserveMet\x12\x1d\n" +
	"\n" +
	"total_bids\x18\v \x01(\x05R\ttotalBidsB\x10\n" +
	"\x0e_current_priceB\x11\n" +
	"\x0f_winner_user_id\"\x95\x01\n" +
	"\x03Bid\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\tR\tauctionId\x12\x1b\n" +
	"\tbidder_id\x18\x03 \x01(\tR\bbidderId\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x04 \x01(\x01R\tbidAmount\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"W\n" +
	"\x13ListAuctionsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8b\x01\n" +
	"\x14ListAuctionsResponse\x12,\n" +
	"\bauctions\x18\x01 \x03(\v2\x10.auction.AuctionR\bauctions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xd0\x01\n" +
	"\x14CreateAuctionRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x03R\bsellerId\x12%\n" +
	"\x0estarting_price\x18\x03 \x01(\x01R\rstartingPrice\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12(\n" +
	"\rreserve_price\x18\x05 \x01(\x01H\x00R\freservePrice\x88\x01\x01B\x10\n" +
	"\x0e_reserve_price\"C\n" +
	"\x15CreateAuctionResponse\x12*\n" +
	"\aauction\x18\x01 \x01(\v2\x10.auction.AuctionR\aauction\"2\n" +
	"\x11GetAuctionRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\"@\n" +
	"\x12GetAuctionResponse\x12*\n" +
	"\aauction\x18\x01 \x01(\v2\x10.auction.AuctionR\aauction\"N\n" +
	"\x14DeleteAuctionRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15DeleteAuctionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\x0fPlaceBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x1b\n" +
	"\tbidder_id\x18\x02 \x01(\tR\bbidderId\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x03 \x01(\x01R\tbidAmount\"2\n" +
	"\x10PlaceBidResponse\x12\x1e\n" +
	"\x03bid\x18\x01 \x01(\v2\f.auction.BidR\x03bid\"`\n" +
	"\x15GetAuctionBidsRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x81\x01\n" +
	"\x16GetAuctionBidsResponse\x12 \n" +
	"\x04bids\x18\x01 \x03(\v2\f.auction.BidR\x04bids\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xdf\x03\n" +
	"\x0eAuctionService\x12K\n" +
	"\fListAuctions\x12\x1c.auction.ListAuctionsRequest\x1a\x1d.auction.ListAuctionsResponse\x12N\n" +
	"\rCreateAuction\x12\x1d.auction.CreateAuctionRequest\x1a\x1e.auction.CreateAuctionResponse\x12L\n" +
	"\x11GetAuctionDetails\x12\x1a.auction.GetAuctionRequest\x1a\x1b.auction.GetAuctionResponse\x12N\n" +
	"\rDeleteAuction\x12\x1d.auction.DeleteAuctionRequest\x1a\x1e.auction.DeleteAuctionResponse\x12?\n" +
	"\bPlaceBid\x12\x18.auction.PlaceBidRequest\x1a\x19.auction.PlaceBidResponse\x12Q\n" +
	"\x0eGetAuctionBids\x12\x1e.auction.GetAuctionBidsRequest\x1a\x1f.auction.GetAuctionBidsResponseB\tZ\a./protob\x06proto3"

var (
	file_auction_proto_auction_proto_rawDescOnce sync.Once
	file_auction_proto_auction_proto_rawDescData []byte
)

func file_auction_proto_auction_proto_rawDescGZIP() []byte {
	file_auction_proto_auction_proto_rawDescOnce.Do(func() {
		file_auction_proto_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_proto_auction_proto_rawDesc), len(file_auction_proto_auction_proto_rawDesc)))
	})
	return file_auction_proto_auction_proto_rawDescData
}

var file_auction_proto_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auction_proto_auction_proto_goTypes = []any{
	(*Auction)(nil),                // 0: auction.Auction
	(*Bid)(nil),                    // 1: auction.Bid
	(*ListAuctionsRequest)(nil),    // 2: auction.ListAuctionsRequest
	(*ListAuctionsResponse)(nil),   // 3: auction.ListAuctionsResponse
	(*CreateAuctionRequest)(nil),   // 4: auction.CreateAuctionRequest
	(*CreateAuctionResponse)(nil),  // 5: auction.CreateAuctionResponse
	(*GetAuctionRequest)(nil),      // 6: auction.GetAuctionRequest
	(*GetAuctionResponse)(nil),     // 7: auction.GetAuctionResponse
	(*DeleteAuctionRequest)(nil),   // 8: auction.DeleteAuctionRequest
	(*DeleteAuctionResponse)(nil),  // 9: auction.DeleteAuctionResponse
	(*PlaceBidRequest)(nil),        // 10: auction.PlaceBidRequest
	(*PlaceBidResponse)(nil),       // 11: auction.PlaceBidResponse
	(*GetAuctionBidsRequest)(nil),  // 12: auction.GetAuctionBidsRequest
	(*GetAuctionBidsResponse)(nil), // 13: auction.GetAuctionBidsResponse
}
var file_auction_proto_auction_proto_depIdxs = []int32{
	0,  // 0: auction.ListAuctionsResponse.auctions:type_name -> auction.Auction
	0,  // 1: auction.CreateAuctionResponse.auction:type_name -> auction.Auction
	0,  // 2: auction.GetAuctionResponse.auction:type_name -> auction.Auction
	1,  // 3: auction.PlaceBidResponse.bid:type_name -> auction.Bid
	1,  // 4: auction.GetAuctionBidsResponse.bids:type_name -> auction.Bid
	2,  // 5: auction.AuctionService.ListAuctions:input_type -> auction.ListAuctionsRequest
	4,  // 6: auction.AuctionService.CreateAuction:input_type -> auction.CreateAuctionRequest
	6,  // 7: auction.AuctionService.GetAuctionDetails:input_type -> auction.GetAuctionRequest
	8,  // 8: auction.AuctionService.DeleteAuction:input_type -> auction.DeleteAuctionRequest
	10, // 9: auction.AuctionService.PlaceBid:input_type -> auction.PlaceBidRequest
	12, // 10: auction.AuctionService.GetAuctionBids:input_type -> auction.GetAuctionBidsRequest
	3,  // 11: auction.AuctionService.ListAuctions:output_type -> auction.ListAuctionsResponse
	5,  // 12: auction.AuctionService.CreateAuction:output_type -> auction.CreateAuctionResponse
	7,  // 13: auction.AuctionService.GetAuctionDetails:output_type -> auction.GetAuctionResponse
	9,  // 14: auction.AuctionService.DeleteAuction:output_type -> auction.DeleteAuctionResponse
	11, // 15: auction.AuctionService.PlaceBid:output_type -> auction.PlaceBidResponse
	13, // 16: auction.AuctionService.GetAuctionBids:output_type -> auction.GetAuctionBidsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_auction_proto_auction_proto_init() }
func file_auction_proto_auction_proto_init() {
	if File_auction_proto_auction_proto != nil {
		return
	}
	file_auction_proto_auction_proto_msgTypes[0].OneofWrappers = []any{}
	file_auction_proto_auction_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_proto_auction_proto_rawDesc), len(file_auction_proto_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_proto_auction_proto_goTypes,
		DependencyIndexes: file_auction_proto_auction_proto_depIdxs,
		MessageInfos:      file_auction_proto_auction_proto_msgTypes,
	}.Build()
	File_auction_proto_auction_proto = out.File
	file_auction_proto_auction_proto_goTypes = nil
	file_auction_proto_auction_proto_depIdxs = nil
}
