// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: listing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Listing) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Listing) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Listing) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Listing) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *Listing) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Listing) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

type ListingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsRequest) Reset() {
	*x = ListingDetailsRequest{}
	mi := &file_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsRequest) ProtoMessage() {}

func (x *ListingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsRequest.ProtoReflect.Descriptor instead.
func (*ListingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{1}
}

func (x *ListingDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Trim          string                 `protobuf:"bytes,9,opt,name=trim,proto3" json:"trim,omitempty"`
	Transmission  string                 `protobuf:"bytes,10,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Color         string                 `protobuf:"bytes,11,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,12,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	ListedAt      string                 `protobuf:"bytes,14,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	Images        []string               `protobuf:"bytes,15,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListingDetailsResponse) Reset() {
	*x = ListingDetailsResponse{}
	mi := &file_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingDetailsResponse) ProtoMessage() {}

func (x *ListingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingDetailsResponse.ProtoReflect.Descriptor instead.
func (*ListingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ListingDetailsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingDetailsResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *ListingDetailsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListingDetailsResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListingDetailsResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingDetailsResponse) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *ListingDetailsResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListingDetailsResponse) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *ListingDetailsResponse) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *ListingDetailsResponse) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *ListingDetailsResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ListingDetailsResponse) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *ListingDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingDetailsResponse) GetListedAt() string {
	if x != nil {
		return x.ListedAt
	}
	return ""
}

func (x *ListingDetailsResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CompareListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsRequest) Reset() {
	*x = CompareListingsRequest{}
	mi := &file_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsRequest) ProtoMessage() {}

func (x *CompareListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsRequest.ProtoReflect.Descriptor instead.
func (*CompareListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{3}
}

func (x *CompareListingsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CompareListingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Listings      []*ListingDetailsResponse `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareListingsResponse) Reset() {
	*x = CompareListingsResponse{}
	mi := &file_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareListingsResponse) ProtoMessage() {}

func (x *CompareListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareListingsResponse.ProtoReflect.Descriptor instead.
func (*CompareListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{4}
}

func (x *CompareListingsResponse) GetListings() []*ListingDetailsResponse {
	if x != nil {
		return x.Listings
	}
	return nil
}

type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Make          string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,5,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,7,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Trim          string                 `protobuf:"bytes,8,opt,name=trim,proto3" json:"trim,omitempty"`
	Transmission  string                 `protobuf:"bytes,9,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Color         string                 `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,11,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	Description   string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{5}
}

func (x *CreateListingRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CreateListingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateListingRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateListingRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *CreateListingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateListingRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *CreateListingRequest) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *CreateListingRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *CreateListingRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateListingRequest) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *CreateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateListingRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type UpdateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Trim          string                 `protobuf:"bytes,9,opt,name=trim,proto3" json:"trim,omitempty"`
	Transmission  string                 `protobuf:"bytes,10,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Color         string                 `protobuf:"bytes,11,opt,name=color,proto3" json:"color,omitempty"`
	SellerType    string                 `protobuf:"bytes,12,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,14,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListingRequest) Reset() {
	*x = UpdateListingRequest{}
	mi := &file_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListingRequest) ProtoMessage() {}

func (x *UpdateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListingRequest.ProtoReflect.Descriptor instead.
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateListingRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *UpdateListingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateListingRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateListingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateListingRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *UpdateListingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateListingRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *UpdateListingRequest) GetTrim() string {
	if x != nil {
		return x.Trim
	}
	return ""
}

func (x *UpdateListingRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *UpdateListingRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateListingRequest) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *UpdateListingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateListingRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type DeleteListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingRequest) Reset() {
	*x = DeleteListingRequest{}
	mi := &file_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingRequest) ProtoMessage() {}

func (x *DeleteListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteListingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListingResponse) Reset() {
	*x = DeleteListingResponse{}
	mi := &file_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListingResponse) ProtoMessage() {}

func (x *DeleteListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListingResponse.ProtoReflect.Descriptor instead.
func (*DeleteListingResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteListingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckListingOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	DealerId      int64                  `protobuf:"varint,2,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOwnershipRequest) Reset() {
	*x = CheckListingOwnershipRequest{}
	mi := &file_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOwnershipRequest) ProtoMessage() {}

func (x *CheckListingOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOwnershipRequest.ProtoReflect.Descriptor instead.
func (*CheckListingOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{9}
}

func (x *CheckListingOwnershipRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *CheckListingOwnershipRequest) GetDealerId() int64 {
	if x != nil {
		return x.DealerId
	}
	return 0
}

type CheckListingOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOwner       bool                   `protobuf:"varint,1,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOwnershipResponse) Reset() {
	*x = CheckListingOwnershipResponse{}
	mi := &file_listing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOwnershipResponse) ProtoMessage() {}

func (x *CheckListingOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOwnershipResponse.ProtoReflect.Descriptor instead.
func (*CheckListingOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{10}
}

func (x *CheckListingOwnershipResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type CheckListingOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOpenRequest) Reset() {
	*x = CheckListingOpenRequest{}
	mi := &file_listing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOpenRequest) ProtoMessage() {}

func (x *CheckListingOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOpenRequest.ProtoReflect.Descriptor instead.
func (*CheckListingOpenRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{11}
}

func (x *CheckListingOpenRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

type CheckListingOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckListingOpenResponse) Reset() {
	*x = CheckListingOpenResponse{}
	mi := &file_listing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckListingOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckListingOpenResponse) ProtoMessage() {}

func (x *CheckListingOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckListingOpenResponse.ProtoReflect.Descriptor instead.
func (*CheckListingOpenResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{12}
}

func (x *CheckListingOpenResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

var File_listing_proto protoreflect.FileDescriptor

const file_listing_proto_rawDesc = "" +
	"\n" +
	"\rlisting.proto\x12\alisting\"\xc0\x01\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\"'\n" +
	"\x15ListingDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x95\x03\n" +
	"\x16ListingDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x12\n" +
	"\x04trim\x18\t \x01(\tR\x04trim\x12\"\n" +
	"\ftransmission\x18\n" +
	" \x01(\tR\ftransmission\x12\x14\n" +
	"\x05color\x18\v \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\f \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x1b\n" +
	"\tlisted_at\x18\x0e \x01(\tR\blistedAt\x12\x16\n" +
	"\x06images\x18\x0f \x03(\tR\x06images\"*\n" +
	"\x16CompareListingsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"V\n" +
	"\x17CompareListingsResponse\x12;\n" +
	"\blistings\x18\x01 \x03(\v2\x1f.listing.ListingDetailsResponseR\blistings\"\xe6\x02\n" +
	"\x14CreateListingRequest\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x05 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\a \x01(\tR\bfuelType\x12\x12\n" +
	"\x04trim\x18\b \x01(\tR\x04trim\x12\"\n" +
	"\ftransmission\x18\t \x01(\tR\ftransmission\x12\x14\n" +
	"\x05color\x18\n" +
	" \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\v \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06images\"\xf6\x02\n" +
	"\x14UpdateListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x12\n" +
	"\x04trim\x18\t \x01(\tR\x04trim\x12\"\n" +
	"\ftransmission\x18\n" +
	" \x01(\tR\ftransmission\x12\x14\n" +
	"\x05color\x18\v \x01(\tR\x05color\x12\x1f\n" +
	"\vseller_type\x18\f \x01(\tR\n" +
	"sellerType\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x0e \x03(\tR\x06images\"&\n" +
	"\x14DeleteListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x15DeleteListingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x1cCheckListingOwnershipRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\x12\x1b\n" +
	"\tdealer_id\x18\x02 \x01(\x03R\bdealerId\":\n" +
	"\x1dCheckListingOwnershipResponse\x12\x19\n" +
	"\bis_owner\x18\x01 \x01(\bR\aisOwner\"8\n" +
	"\x17CheckListingOpenRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\"3\n" +
	"\x18CheckListingOpenResponse\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen2\xef\x04\n" +
	"\x0eListingService\x12T\n" +
	"\x11GetListingDetails\x12\x1e.listing.ListingDetailsRequest\x1a\x1f.listing.ListingDetailsResponse\x12T\n" +
	"\x0fCompareListings\x12\x1f.listing.CompareListingsRequest\x1a .listing.CompareListingsResponse\x12O\n" +
	"\rCreateListing\x12\x1d.listing.CreateListingRequest\x1a\x1f.listing.ListingDetailsResponse\x12O\n" +
	"\rUpdateListing\x12\x1d.listing.UpdateListingRequest\x1a\x1f.listing.ListingDetailsResponse\x12N\n" +
	"\rDeleteListing\x12\x1d.listing.DeleteListingRequest\x1a\x1e.listing.DeleteListingResponse\x12f\n" +
	"\x15CheckListingOwnership\x12%.listing.CheckListingOwnershipRequest\x1a&.listing.CheckListingOwnershipResponse\x12W\n" +
	"\x10CheckListingOpen\x12 .listing.CheckListingOpenRequest\x1a!.listing.CheckListingOpenResponseB\tZ\a./protob\x06proto3"

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData []byte
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)))
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_listing_proto_goTypes = []any{
	(*Listing)(nil),                       // 0: listing.Listing
	(*ListingDetailsRequest)(nil),         // 1: listing.ListingDetailsRequest
	(*ListingDetailsResponse)(nil),        // 2: listing.ListingDetailsResponse
	(*CompareListingsRequest)(nil),        // 3: listing.CompareListingsRequest
	(*CompareListingsResponse)(nil),       // 4: listing.CompareListingsResponse
	(*CreateListingRequest)(nil),          // 5: listing.CreateListingRequest
	(*UpdateListingRequest)(nil),          // 6: listing.UpdateListingRequest
	(*DeleteListingRequest)(nil),          // 7: listing.DeleteListingRequest
	(*DeleteListingResponse)(nil),         // 8: listing.DeleteListingResponse
	(*CheckListingOwnershipRequest)(nil),  // 9: listing.CheckListingOwnershipRequest
	(*CheckListingOwnershipResponse)(nil), // 10: listing.CheckListingOwnershipResponse
	(*CheckListingOpenRequest)(nil),       // 11: listing.CheckListingOpenRequest
	(*CheckListingOpenResponse)(nil),      // 12: listing.CheckListingOpenResponse
}
var file_listing_proto_depIdxs = []int32{
	2,  // 0: listing.CompareListingsResponse.listings:type_name -> listing.ListingDetailsResponse
	1,  // 1: listing.ListingService.GetListingDetails:input_type -> listing.ListingDetailsRequest
	3,  // 2: listing.ListingService.CompareListings:input_type -> listing.CompareListingsRequest
	5,  // 3: listing.ListingService.CreateListing:input_type -> listing.CreateListingRequest
	6,  // 4: listing.ListingService.UpdateListing:input_type -> listing.UpdateListingRequest
	7,  // 5: listing.ListingService.DeleteListing:input_type -> listing.DeleteListingRequest
	9,  // 6: listing.ListingService.CheckListingOwnership:input_type -> listing.CheckListingOwnershipRequest
	11, // 7: listing.ListingService.CheckListingOpen:input_type -> listing.CheckListingOpenRequest
	2,  // 8: listing.ListingService.GetListingDetails:output_type -> listing.ListingDetailsResponse
	4,  // 9: listing.ListingService.CompareListings:output_type -> listing.CompareListingsResponse
	2,  // 10: listing.ListingService.CreateListing:output_type -> listing.ListingDetailsResponse
	2,  // 11: listing.ListingService.UpdateListing:output_type -> listing.ListingDetailsResponse
	8,  // 12: listing.ListingService.DeleteListing:output_type -> listing.DeleteListingResponse
	10, // 13: listing.ListingService.CheckListingOwnership:output_type -> listing.CheckListingOwnershipResponse
	12, // 14: listing.ListingService.CheckListingOpen:output_type -> listing.CheckListingOpenResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
