// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: user/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileRequest) Reset() {
	*x = CreateUserProfileRequest{}
	mi := &file_user_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileRequest) ProtoMessage() {}

func (x *CreateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileResponse) Reset() {
	*x = CreateUserProfileResponse{}
	mi := &file_user_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileResponse) ProtoMessage() {}

func (x *CreateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFavoritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesRequest) Reset() {
	*x = GetFavoritesRequest{}
	mi := &file_user_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesRequest) ProtoMessage() {}

func (x *GetFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesRequest.ProtoReflect.Descriptor instead.
func (*GetFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetFavoritesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FavoritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorites     []int64                `protobuf:"varint,1,rep,packed,name=favorites,proto3" json:"favorites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoritesResponse) Reset() {
	*x = FavoritesResponse{}
	mi := &file_user_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoritesResponse) ProtoMessage() {}

func (x *FavoritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoritesResponse.ProtoReflect.Descriptor instead.
func (*FavoritesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *FavoritesResponse) GetFavorites() []int64 {
	if x != nil {
		return x.Favorites
	}
	return nil
}

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_user_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *AddFavoriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddFavoriteRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_user_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFavoriteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFavoriteRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

type FavoriteMutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteMutationResponse) Reset() {
	*x = FavoriteMutationResponse{}
	mi := &file_user_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteMutationResponse) ProtoMessage() {}

func (x *FavoriteMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteMutationResponse.ProtoReflect.Descriptor instead.
func (*FavoriteMutationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *FavoriteMutationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FavoriteMutationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UsersPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersPreviewRequest) Reset() {
	*x = UsersPreviewRequest{}
	mi := &file_user_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersPreviewRequest) ProtoMessage() {}

func (x *UsersPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersPreviewRequest.ProtoReflect.Descriptor instead.
func (*UsersPreviewRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UsersPreviewRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreview) Reset() {
	*x = UserPreview{}
	mi := &file_user_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreview) ProtoMessage() {}

func (x *UserPreview) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreview.ProtoReflect.Descriptor instead.
func (*UserPreview) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserPreview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPreview) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UsersPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserPreview         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersPreviewResponse) Reset() {
	*x = UsersPreviewResponse{}
	mi := &file_user_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersPreviewResponse) ProtoMessage() {}

func (x *UsersPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersPreviewResponse.ProtoReflect.Descriptor instead.
func (*UsersPreviewResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *UsersPreviewResponse) GetUsers() []*UserPreview {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_user_proto_user_proto protoreflect.FileDescriptor

const file_user_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x15user/proto/user.proto\x12\x04user\"]\n" +
	"\x18CreateUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"5\n" +
	"\x19CreateUserProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13GetFavoritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"1\n" +
	"\x11FavoritesResponse\x12\x1c\n" +
	"\tfavorites\x18\x01 \x03(\x03R\tfavorites\"L\n" +
	"\x12AddFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\"O\n" +
	"\x15RemoveFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\"N\n" +
	"\x18FavoriteMutationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x13UsersPreviewRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"1\n" +
	"\vUserPreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\x14UsersPreviewResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.user.UserPreviewR\x05users2\x89\x03\n" +
	"\vUserService\x12B\n" +
	"\fGetFavorites\x12\x19.user.GetFavoritesRequest\x1a\x17.user.FavoritesResponse\x12G\n" +
	"\vAddFavorite\x12\x18.user.AddFavoriteRequest\x1a\x1e.user.FavoriteMutationResponse\x12M\n" +
	"\x0eRemoveFavorite\x12\x1b.user.RemoveFavoriteRequest\x1a\x1e.user.FavoriteMutationResponse\x12H\n" +
	"\x0fGetUsersPreview\x12\x19.user.UsersPreviewRequest\x1a\x1a.user.UsersPreviewResponse\x12T\n" +
	"\x11CreateUserProfile\x12\x1e.user.CreateUserProfileRequest\x1a\x1f.user.CreateUserProfileResponseB\tZ\a./protob\x06proto3"

var (
	file_user_proto_user_proto_rawDescOnce sync.Once
	file_user_proto_user_proto_rawDescData []byte
)

func file_user_proto_user_proto_rawDescGZIP() []byte {
	file_user_proto_user_proto_rawDescOnce.Do(func() {
		file_user_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_user_proto_rawDesc), len(file_user_proto_user_proto_rawDesc)))
	})
	return file_user_proto_user_proto_rawDescData
}

var file_user_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_user_proto_goTypes = []any{
	(*CreateUserProfileRequest)(nil),  // 0: user.CreateUserProfileRequest
	(*CreateUserProfileResponse)(nil), // 1: user.CreateUserProfileResponse
	(*GetFavoritesRequest)(nil),       // 2: user.GetFavoritesRequest
	(*FavoritesResponse)(nil),         // 3: user.FavoritesResponse
	(*AddFavoriteRequest)(nil),        // 4: user.AddFavoriteRequest
	(*RemoveFavoriteRequest)(nil),     // 5: user.RemoveFavoriteRequest
	(*FavoriteMutationResponse)(nil),  // 6: user.FavoriteMutationResponse
	(*UsersPreviewRequest)(nil),       // 7: user.UsersPreviewRequest
	(*UserPreview)(nil),               // 8: user.UserPreview
	(*UsersPreviewResponse)(nil),      // 9: user.UsersPreviewResponse
}
var file_user_proto_user_proto_depIdxs = []int32{
	8, // 0: user.UsersPreviewResponse.users:type_name -> user.UserPreview
	2, // 1: user.UserService.GetFavorites:input_type -> user.GetFavoritesRequest
	4, // 2: user.UserService.AddFavorite:input_type -> user.AddFavoriteRequest
	5, // 3: user.UserService.RemoveFavorite:input_type -> user.RemoveFavoriteRequest
	7, // 4: user.UserService.GetUsersPreview:input_type -> user.UsersPreviewRequest
	0, // 5: user.UserService.CreateUserProfile:input_type -> user.CreateUserProfileRequest
	3, // 6: user.UserService.GetFavorites:output_type -> user.FavoritesResponse
	6, // 7: user.UserService.AddFavorite:output_type -> user.FavoriteMutationResponse
	6, // 8: user.UserService.RemoveFavorite:output_type -> user.FavoriteMutationResponse
	9, // 9: user.UserService.GetUsersPreview:output_type -> user.UsersPreviewResponse
	1, // 10: user.UserService.CreateUserProfile:output_type -> user.CreateUserProfileResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_user_proto_init() }
func file_user_proto_user_proto_init() {
	if File_user_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_user_proto_rawDesc), len(file_user_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_user_proto_goTypes,
		DependencyIndexes: file_user_proto_user_proto_depIdxs,
		MessageInfos:      file_user_proto_user_proto_msgTypes,
	}.Build()
	File_user_proto_user_proto = out.File
	file_user_proto_user_proto_goTypes = nil
	file_user_proto_user_proto_depIdxs = nil
}
