apiVersion: v1
kind: Secret
metadata:
  name: auction-secrets
  namespace: vehicles-prod
type: Opaque
stringData:
  postgres-dsn: postgres://auction_user:auction_password@auction-db.vehicles-prod.svc.cluster.local:5432/auction_db?sslmode=disable
  gcp-project-id: cn-project-491618
