apiVersion: v1
kind: Secret
metadata:
  name: auth-env
  namespace: vehicles-prod
type: Opaque
stringData:
  AUTH_DATABASE_URL: postgres://auth_user:auth_password@auth-db:5432/auth_db?sslmode=disable
  AUTH_POSTGRES_DB: auth_db
  AUTH_POSTGRES_USER: auth_user
  AUTH_POSTGRES_PASSWORD: auth_password
  JWT_PRIVATE_KEY_B64: private_key
