apiVersion: v1
kind: Secret
metadata:
  name: listing-search-env
  namespace: vehicles-prod
type: Opaque
stringData:
  # TODO: Replace the URL
  LISTING_DATABASE_URL: postgres://listing_user:change-me@listing-db.vehicles-prod.svc.cluster.local:5432/listing_db?sslmode=disable
  LISTING_POSTGRES_DB: listing_db
  LISTING_POSTGRES_USER: listing_user
  LISTING_POSTGRES_PASSWORD: change-me
