apiVersion: v1
kind: Secret
metadata:
  name: seller-env
  namespace: vehicles-prod
type: Opaque
stringData:
  SELLER_DATABASE_URL: postgres://seller_user:change-me@seller-db.vehicles-prod.svc.cluster.local:5432/seller_db?sslmode=disable
  SELLER_POSTGRES_DB: seller_db
  SELLER_POSTGRES_USER: seller_user
  SELLER_POSTGRES_PASSWORD: change-me
  LISTING_DATABASE_URL: postgres://listing_user:change-me@listing-db.vehicles-prod.svc.cluster.local:5432/listing_db?sslmode=disable
