apiVersion: v1
kind: ServiceAccount
metadata:
  name: vehicles-workload-sa
  namespace: vehicles-prod
  annotations:
    iam.gke.io/gcp-service-account: vehicles-svc@cn-project-491618.iam.gserviceaccount.com