apiVersion: v1
kind: Secret
metadata:
  name: user-env
  namespace: vehicles-prod
type: Opaque
stringData:
  USER_DATABASE_URL: postgres://user_user:change-me@user-db.vehicles-prod.svc.cluster.local:5432/user_db?sslmode=disable
  USER_POSTGRES_DB: user_db
  USER_POSTGRES_USER: user_user
  USER_POSTGRES_PASSWORD: change-me
