apiVersion: v1
kind: Service
metadata:
  name: marketprice-service
  namespace: vehicles-prod
  labels:
    app: marketprice-service
spec:
  type: ClusterIP
  selector:
    app: marketprice-service
  ports:
    - name: grpc
      port: 50055
      targetPort: grpc