apiVersion: v1
kind: Service
metadata:
  name: marketprice
  namespace: vehicles-prod
  labels:
    app: marketprice
spec:
  type: ClusterIP
  selector:
    app: marketprice
  ports:
    - name: grpc
      port: 50055
      targetPort: grpc