// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: seller/proto/seller.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SellerService_GetSellerProfile_FullMethodName    = "/seller.SellerService/GetSellerProfile"
	SellerService_CreateSeller_FullMethodName        = "/seller.SellerService/CreateSeller"
	SellerService_VerifySellerProfile_FullMethodName = "/seller.SellerService/VerifySellerProfile"
	SellerService_CreateListing_FullMethodName       = "/seller.SellerService/CreateListing"
)

// SellerServiceClient is the client API for SellerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerServiceClient interface {
	GetSellerProfile(ctx context.Context, in *GetSellerProfileRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error)
	CreateSeller(ctx context.Context, in *CreateSellerRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error)
	VerifySellerProfile(ctx context.Context, in *VerifySellerRequest, opts ...grpc.CallOption) (*VerifySellerResponse, error)
	CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*CreateListingResponse, error)
}

type sellerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerServiceClient(cc grpc.ClientConnInterface) SellerServiceClient {
	return &sellerServiceClient{cc}
}

func (c *sellerServiceClient) GetSellerProfile(ctx context.Context, in *GetSellerProfileRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellerProfileResponse)
	err := c.cc.Invoke(ctx, SellerService_GetSellerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) CreateSeller(ctx context.Context, in *CreateSellerRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellerProfileResponse)
	err := c.cc.Invoke(ctx, SellerService_CreateSeller_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) VerifySellerProfile(ctx context.Context, in *VerifySellerRequest, opts ...grpc.CallOption) (*VerifySellerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySellerResponse)
	err := c.cc.Invoke(ctx, SellerService_VerifySellerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*CreateListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateListingResponse)
	err := c.cc.Invoke(ctx, SellerService_CreateListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerServiceServer is the server API for SellerService service.
// All implementations must embed UnimplementedSellerServiceServer
// for forward compatibility.
type SellerServiceServer interface {
	GetSellerProfile(context.Context, *GetSellerProfileRequest) (*SellerProfileResponse, error)
	CreateSeller(context.Context, *CreateSellerRequest) (*SellerProfileResponse, error)
	VerifySellerProfile(context.Context, *VerifySellerRequest) (*VerifySellerResponse, error)
	CreateListing(context.Context, *CreateListingRequest) (*CreateListingResponse, error)
	mustEmbedUnimplementedSellerServiceServer()
}

// UnimplementedSellerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSellerServiceServer struct{}

func (UnimplementedSellerServiceServer) GetSellerProfile(context.Context, *GetSellerProfileRequest) (*SellerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSellerProfile not implemented")
}
func (UnimplementedSellerServiceServer) CreateSeller(context.Context, *CreateSellerRequest) (*SellerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeller not implemented")
}
func (UnimplementedSellerServiceServer) VerifySellerProfile(context.Context, *VerifySellerRequest) (*VerifySellerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySellerProfile not implemented")
}
func (UnimplementedSellerServiceServer) CreateListing(context.Context, *CreateListingRequest) (*CreateListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateListing not implemented")
}
func (UnimplementedSellerServiceServer) mustEmbedUnimplementedSellerServiceServer() {}
func (UnimplementedSellerServiceServer) testEmbeddedByValue()                       {}

// UnsafeSellerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerServiceServer will
// result in compilation errors.
type UnsafeSellerServiceServer interface {
	mustEmbedUnimplementedSellerServiceServer()
}

func RegisterSellerServiceServer(s grpc.ServiceRegistrar, srv SellerServiceServer) {
	// If the following call panics, it indicates UnimplementedSellerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SellerService_ServiceDesc, srv)
}

func _SellerService_GetSellerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).GetSellerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_GetSellerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).GetSellerProfile(ctx, req.(*GetSellerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_CreateSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).CreateSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_CreateSeller_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).CreateSeller(ctx, req.(*CreateSellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_VerifySellerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).VerifySellerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_VerifySellerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).VerifySellerProfile(ctx, req.(*VerifySellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_CreateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).CreateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_CreateListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).CreateListing(ctx, req.(*CreateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerService_ServiceDesc is the grpc.ServiceDesc for SellerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seller.SellerService",
	HandlerType: (*SellerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSellerProfile",
			Handler:    _SellerService_GetSellerProfile_Handler,
		},
		{
			MethodName: "CreateSeller",
			Handler:    _SellerService_CreateSeller_Handler,
		},
		{
			MethodName: "VerifySellerProfile",
			Handler:    _SellerService_VerifySellerProfile_Handler,
		},
		{
			MethodName: "CreateListing",
			Handler:    _SellerService_CreateListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller/proto/seller.proto",
}
